IP2-83 - initialize springboot
intive/patronage21-java pull request #1
Opened 2021-03-19 20:52 UTC by kari565

2021-03-20 08:00 UTC, KrzysztofPawlak approved these changes

2021-03-22 09:46 UTC, patronage-java-leaders-2021 requested changes

2021-03-22 09:46 UTC, patronage-java-leaders-2021 commented on build.gradle
> +	annotationProcessor 'org.projectlombok:lombok'
Proponowałbym dodanie obsługi Lomboka także do wykorzystania na etapie testów.

2021-03-22 12:20 UTC, patronage-java-leaders-2021 approved these changes

2021-03-22 12:43 UTC, P-Brzezinski commented
Approved

2021-03-22 12:45 UTC, P-Brzezinski commented
Ok

2021-03-22 12:56 UTC, P-Brzezinski approved these changes
Approved

2021-03-22 12:59 UTC, merged