Added service for querying users by role
intive/patronage21-java pull request #10
Opened 2021-03-23 23:10 UTC by LukaszCzeronko

2021-03-24 07:22 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/service/UserDisplayService.java
> +    // set bean to preload default set of data
komentarz jest niepotrzebny, najlepiej jak nazwa metody mówi co wykonuje

2021-03-24 07:22 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/service/UserDisplayService.java
> +    //search and return users with given role
komentarz jest niepotrzebny, najlepiej jak nazwa metody mówi co wykonuje

2021-03-24 07:22 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/service/UserDisplayService.java
> +    //map user entity to user dto
komentarz jest niepotrzebny, najlepiej jak nazwa metody mówi co wykonuje

2021-03-25 20:37 UTC, kari565 commented on src/main/java/com/intive/patronative/service/UserDisplayService.java
> +    @Bean
Czemu tu jest tworzony @Bean, który dodaje elementy do listy? Czy ma to jakąś zaletę względem dodania tych elementów w kostruktorze?

2021-03-26 11:16 UTC, patronage-java-leaders-2021 requested changes

2021-03-26 11:16 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/UserDisplayService.java
> +    public void setUsers() {
Starajmy się pisać prosty i czytelny kod (KISS rule: simplicity should be a key goal in design, and unnecessary complexity should be avoided), który będzie łatwy w utrzymaniu. Dostarczona funkcjonalność moze, i powinna, zostać zrealizowana prościej z wykorzystaniem podstawowych mechanizmów Javy i Java Collection API. 
Zdefiniuj proszę interface który będzie udostępniał odpowiednią metodę przygotowującą zamockowane dane. W klasie implementującej interface proszę przygotować funkcjonalność mocka. Następnie wstrzyknij interface do klasy serwisowej i wywołaj utworzoną metodę zasilającą. Proponuję nazwać ją: getAllUseres().

2021-03-26 11:16 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/UserDisplayService.java
> +    private UserDto mapUserToUserDto(User user) {
Klasy serwisowe najczęściej zawierają logikę biznesową aplikacji, zaś wszelkiego rodzaju rozwiązania pomocnicze są delegowane do osobnych klas żeby nie utrudniać analizy sposobu w jaki realizowana jest logika aplikacji. Staramy się tak tworzyć klasy serwisowe, żeby ich analiza pozwoliła w sprawny sposób zorientować się jak działa dany obszar korzystając już z samych nazw metod i ich argumentów. 
Zatem, w tym przypadku mechanizmu mapowania jednego obiektu na drugi, powinien zostać przeniesiony poza klasę z logiką biznesową aplikacji. 
Utwórz proszę osobną klasę, np.: com.intive.patronative.mapper.UserMapper albo coś podobnego (wszelkie propozycje mile widziane) i umieść tam wspomnianą metodę. Ponieważ przyjmuje ona jeden parametr, można zrezygnować w nazwie metody z "User", zatem będzie to: mapToUserDto() i zwraca UserDto.

2021-03-26 11:16 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/UserDisplayService.java
> +        return new UserDtoList(userList.stream()
Ponieważ jest to metoda do pobierania listy użytkowników, docelowo będzie ona również odwoływać się do bazy danych. Zatem proponuje aby w ciele metody, pobrać listę użytkowników przy pomocy getAllUseres. Następnie przefiltrować listę użytkowników i zwrócić listę tylko tych którzy spełniają kryteria przekazane do metody.

2021-04-06 11:09 UTC, barbara-tyndorf approved these changes
Wygląda ok.

2021-04-06 12:27 UTC, lzolkiewski approved these changes

2021-04-22 07:08 UTC, closed without merging