IP2-90 - create endpoint for searching users
intive/patronage21-java pull request #11
Opened 2021-03-24 13:01 UTC by lzolkiewski

created validated UserSearchDTO for searching purposes
created UserController making use out of search DTO
created UserService with logging and default list
created User DAO needed in user service
added InvalidArgumentException and its InvalidArgumentAdvice

2021-03-24 21:43 UTC, P-Brzezinski commented on src/main/java/com/intive/patronative/controller/UserController.java
> +            return ResponseEntity.status(HttpStatus.NO_CONTENT).build();
Czy status 204 No Content to dobra odpowiedź? Wydaje mi się, że bardziej odpowiedni będzie tutaj status 200 z pustą listą lub 404 jeżeli nie znajdzie żadnego pojedynczego dopasowania.

2021-03-25 09:00 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/controller/UserController.java
> +            return ResponseEntity.status(HttpStatus.NO_CONTENT).build();
404 nie pasuje mi do wyszukiwania. 
Jeżeli przeszło validację to raczej też nie jest to błąd klienta.
Zastanawiam się nad 204 i 200 ale ciężko stwierdzić, które było by bardziej odpowiednie.

2021-03-25 09:57 UTC, P-Brzezinski approved these changes

2021-03-25 20:56 UTC, kari565 commented on src/main/java/com/intive/patronative/dto/UserSearchDTO.java
> +@Data
Nie lepiej używać @Value? "@Value is the immutable variant of @Data; all fields are made private and final by default, and setters are not generated. The class itself is also made final by default".

2021-03-26 11:49 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/dto/UserSearchDTO.java
> +@Data
Poprawione

2021-03-27 09:49 UTC, patronage-java-leaders-2021 requested changes
@barbara-tyndorf @lzolkiewski 

https://tracker.intive.com/jira/browse/IP2-90 Tutaj jest przypisany całe story ale jednego taska w środku z serwisem robi Barbara. Teraz nie wiem kto co robi, proszę ustalcie między sobą czy nie piszecie tego samego :)

2021-03-27 21:21 UTC, kari565 commented on src/main/java/com/intive/patronative/dto/UserSearchDTO.java
>      @Size(min = 3, max = 50, message = "Surname valid length 3 to 50 characters")
Są ponoć dwuliterowe nazwiska: https://www.znanylekarz.pl/alina-ou/internista/warszawa :)
Co z nazwiskami dwuczłonowymi jak Nowak-Kowalski, czy zawierającymi typowo polskie znaki? 
Można zastosować [AaĄąBbCcĆćDdEeĘęFfGgHhIiJjKkLlŁłMmNnŃńOoÓóPpRrSsŚśTtUuWwYyZzŹźŻż]

Czy nie lepiej zrobić operację, która będzie zwracała dobry wynik niezależnie od wielkości wprowadzonych liter?

2021-03-27 21:21 UTC, kari565 commented on src/main/java/com/intive/patronative/dto/UserSearchDTO.java
>      @Size(min = 3, max = 50, message = "Name valid length 3 to 50 characters")
Znalazłam dwuliterowe imiona obcojęzyczne: https://babynames1000.com/two-letter/

2021-03-27 22:03 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/dto/UserSearchDTO.java
>      @Size(min = 3, max = 50, message = "Surname valid length 3 to 50 characters")
Zastanawiałem się nad tym czy akceptować początek z małej czy nie i na koniec zostawiłem tak w przyszłości może być to zrobione inaczej 

Jeżeli chodzi wielkość to w zadaniu napisane jest minimum 3 stąd taka długość

2021-03-28 12:26 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/dto/UserSearchDTO.java
>      @Size(min = 3, max = 50, message = "Surname valid length 3 to 50 characters")
poprawione by akceptowało polskie znaki,
poprawiono by akceptowało zarówno wielkie jak i małe litery 

co do dwuczłonowych nazwisk nie jestem przekonany dlatego na razie tego nie uwzględniam 
można by poczekać na decyzję klienta z tym

2021-03-28 12:27 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/dto/UserSearchDTO.java
>      @Size(min = 3, max = 50, message = "Name valid length 3 to 50 characters")
W zadaniu jest napisane by wyszukiwanie zaczynało się od podania minimum 3 znaków

2021-03-28 15:56 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/dto/UserDTO.java
> +    @Size(min = 1, max = 50)
wartości można wynieść do osobnego pliku z stałymi, takich klas z nich korzystających będzie pewnie więcej

2021-03-28 15:56 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/dto/UserDTO.java
> +    @Pattern(regexp = "^[A-Za-z0-9_-]+$", message = "Invalid username. Only letters, numbers, underline or dash")
regexy można wynieść do pliku konfiga z stałymi i odpowiednio nazwać

2021-03-28 15:56 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/dto/UserSearchDTO.java
> +    @Size(min = 3, max = 50, message = "Name valid length 3 to 50 characters")
jak już regexy i wartości będą w configu to będzie można je również importować w tych adnotacjach. Będzie łatwiej zarządzać tym z 1 miejsca.

2021-03-28 17:02 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/dto/UserSearchDTO.java
> +    @Size(min = 3, max = 50, message = "Name valid length 3 to 50 characters")
Poprawione
Ograniczenie przeniesione do pliku konfiguracyjnego 
Uwzględnione jedynie w UserSearchDTO przez wzgląd na to, że UserDTO jest jedynie klasą pomocniczą w tym zadaniu i zajmuje się nią ktoś inny

2021-03-29 11:16 UTC, kari565 approved these changes

2021-03-29 15:49 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/config/AppConfig.java
> +//    user search constraints
wg mnie komentarz zbędny ponieważ nazwy stałych mówią same za siebie

2021-03-29 15:53 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/dto/UserSearchDTO.java
> +    @Size(min = SEARCH_USER_MIN_LENGTH, max = SEARCH_USER_MAX_LENGTH, message = "Surname valid length 3 to 50 characters")
Wartości w message też mogą być teraz dynamiczne

2021-03-30 08:01 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/config/AppConfig.java
> +//    user search constraints
Planowałem zostawić to na przyszłość jak będzie więcej wartości w pliku do łatwiejszej nawigacji

2021-04-01 12:30 UTC, patronage-java-leaders-2021 requested changes

2021-04-01 12:30 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/exception/InvalidArgumentAdvice.java
> +public class InvalidArgumentAdvice {
Klasa nie jest wyjątkiem ale ControllerAdvice'm. Proszę o zmianę pakietu na poprawny.

2021-04-01 12:30 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/exception/InvalidArgumentAdvice.java
> +    public Map<String, String> invalidArgumentHandler(InvalidArgumentException exception) {
Ustal proszę z Pawłem Brzezińskim sposób działania mechanizmu walidacji (odpowiednie typy exceptionów, implementacja itp.), tak żeby powstał spójny dla całej aplikacji mechanizm walidacji.

2021-04-01 12:30 UTC, patronage-java-leaders-2021 commented on src/test/java/com/intive/patronative/controller/UserControllerTest.java
> +            , "username=Smith", "username=smith", "username=s123mith", "username=123_mith", "username=123-mith",
Przecinek powinien w poprzedniej linii :)

2021-04-01 12:30 UTC, patronage-java-leaders-2021 commented on src/test/java/com/intive/patronative/controller/UserControllerTest.java
> +                exception.printStackTrace();
Czy pokazanie stacka jest poprawnym zachowaniem, czy testy w tym przypadku powinny failować? Proszę o poprawę.

2021-04-01 12:40 UTC, patronage-java-leaders-2021 requested changes
Proszę o zrealizowanie zmian opisanych w komentarzach. Dziękuję.

2021-04-06 21:03 UTC, KrzysztofPawlak commented on src/test/java/com/intive/patronative/controller/UserControllerTest.java
> +        Arrays.asList(invalidArgsArray).forEach(element -> {
nie wiem, dziwnie to wygląda. Nie da się testami parametryzowanymi?

2021-04-06 21:17 UTC, KrzysztofPawlak commented on src/test/java/com/intive/patronative/controller/UserControllerTest.java
> +    UserService service;
może być private

2021-04-06 21:20 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/controller/UserController.java
> +import org.springframework.beans.factory.annotation.Value;
nadmiarowy import

2021-04-12 15:14 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/dto/UserSearchDTO.java
>      @Size(min = 3, max = 50, message = "Surname valid length 3 to 50 characters")
@lzolkiewski : aplikacja powinna również obsługiwać dwuczłonowe nazwiska :).

2021-04-12 15:36 UTC, patronage-java-leaders-2021 requested changes

2021-04-12 15:36 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/controller/frontend/UserFrontController.java
> +import org.springframework.web.bind.annotation.*;
Proszę o organizację importów. Nie są nam potrzebne wszystkie annotacje dostępne w pakiecie :).

2021-04-12 15:36 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/validation/UserSearchValidator.java
> +    private final int USER_SEARCH_DATA_LENGTH_MIN;
Pole finalne powinno zostać zainicjowane. Co do konwencji zapisu, CAPS_LOCKIEM zapisuje się stałe króte są statyczne.
W tym przypadku domyślam się że zamierzeniem było pobranie parametru konfiguracyjnego z pliku konfiguracyjnego. W takiej sytuacji, nazwa pola powinna być zapisana standardowo, czyli: userSearchDataMinLength, i opatrzone adnotacją @Value.

2021-04-12 15:36 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/validation/UserSearchValidator.java
> +    public UserSearchValidator(@Value("${search.user.data.length.min}") int USER_SEARCH_DATA_LENGTH_MIN) {
Wprowadzając zmianę opisaną wyżej, konstruktor staje się niepotrzebny.
Co do konwencji, nazwy parametrów zawzse pisane są z małej litery, np.: userSearchDataMinLength ;).

2021-04-12 15:36 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/validation/UserSearchValidator.java
> +        return (valueToCheck.length() >= USER_SEARCH_DATA_LENGTH_MIN);
Proszę o dodanie sprawdzenia czy parametr valueToCheck nie jest nullem. W przypadku przekazania nulla, mamy NullPointerException. Zastanów się również proszę, czy nie można wymyślić bardziej "samoopisowej" nazwy dla "valueToCheck" takiej która już po przeczytaniu mówi jaki parametr będzie sprawdzany, i jakie znaczenie biznesowe ma to sprawdzenie. Proszę o poprawkę.
W razie pytań lub wątpliwości, zapraszam do kontaktu :).

2021-04-12 15:36 UTC, patronage-java-leaders-2021 commented on src/main/resources/application.yml
> +search:
Ponieważ są to kryteria konfiguracyjne walidatora, dodaj jeszcze proszę poziom nadrzędny który będzie "łączył" wszyskie pozostałe walidatory. Proponuję nazwać go "validators". Choć wszelkie inne propozycje jak zawsze są mile widziane :).

2021-04-14 20:04 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/validation/UserSearchValidator.java
> +    private final String defaultFirstNameMessage = "Letters only, minimum 2 letters";
userSearchDataMinLength masz już w konfigu wiec można dodać to do msg.

private final String defaultFirstNameMessage = "Letters only, minimum " + userSearchDataMinLength + " letters";

2021-04-19 10:54 UTC, patronage-java-leaders-2021 reviewed
Jest w porządku ale trzeba jeszcze dopisać testy jednostkowe

2021-04-19 10:55 UTC, patronage-java-leaders-2021 requested changes
Testy jednostkowe

2021-04-20 05:58 UTC, patronage-java-leaders-2021 requested changes
Zmienić test który stawia kontekst spring'a

2021-04-20 05:58 UTC, patronage-java-leaders-2021 commented on src/test/java/com/intive/patronative/validation/UserSearchValidatorTest.java
> +class UserSearchValidatorTest {
Ten test nie musi być oznaczony jako @SpringBootTest. A jeżeli nie ma potrzeby nie stawiamy kontekstu Spring'a ze względu na czas odpalania się testów.

2021-04-20 06:09 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/controller/frontend/UserFrontController.java
> +    private void checkSearchDataValidity(UserSearchDTO userSearchDTO) throws MethodArgumentNotValidException, NoSuchMethodException {
Ta logika powinna zostać przeniesiona do metody search do serwisu UserService ponieważ jeżeli ktoś skorzysta z operacji search() nie będzie świadomy o istnieniu walidatora. Kontroler powinien być jak najprostszy i najlepiej jeżeli nie będzie zawierał żadnych metod

2021-04-20 07:15 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/UserService.java
> +    public List<UserDTO> search(UserSearchDTO userSearchDTO) {
Tutaj powinna być robiona walidacja żeby każda osoba która skorzysta z metody nie musiałą pisać osobnej walidacji i o niej pamiętać.

sama metoda może mogłaby zawierać słowo users to z samej nazwy metody na pierwszy rzut oka będzie widać czego on dotyczy

2021-04-20 12:04 UTC, patronage-java-leaders-2021 requested changes
Jeszcze poprawka do zrobienia z Walidatorami :)

2021-04-22 08:07 UTC, patronage-java-leaders-2021 approved these changes

2021-04-22 08:42 UTC, merged