Wip ip2 88 Add UserController and UserService for User registration
intive/patronage21-java pull request #12
Opened 2021-03-24 13:19 UTC by P-Brzezinski

2021-03-24 13:38 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/dto/UserDTO.java
> +    private String userName;
Mógłbyś w walidacji zawrzeć więcej szczegółów 
W tym momencie przyjmie ci dowolny tekst z @ w środku mógłbyś dodać  jeszcze regex na kropkę i rozszerzenie domeny  
w stringach masz adnotację @Patern i możesz tam dodać więcej szczegółów niż tylko NotBlank

2021-03-24 13:53 UTC, P-Brzezinski commented on src/main/java/com/intive/patronative/dto/UserDTO.java
> +    private String userName;
Szczerze to zastanawiałem się nad bardziej szczegółową walidacją ale stwierdziłem że nie znam wymagań co do np . userName itp. Ale masz rację, email czy nawet gitHubUrl można określić jakimś pattern. Zabiorę się za to.

2021-03-29 10:00 UTC, patronage-java-leaders-2021 requested changes

2021-03-29 10:00 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/controller/UserController.java
> +    public ResponseEntity<String> saveUser(@Valid @RequestBody UserDTO userDTO){
Metoda realizująca zapis danych powinna być void'em. Informacja o pomyślnym zapisaniu danych lub o niepowodzeniu powinna zostać zwrócona z wykorzystaniem odowiednich statusów HTTP.

2021-03-29 10:00 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/dto/UserDTO.java
> +public class UserDTO {
Klasa DTO powinna zostać wykorzystana do transferu danych. Walidacja danych powinna zostać oddelegowana do dedykowanego walidatora który powinien zweryfikować poprawność otrzymanych danych zanim rozpoczęte zostanie przetwarzanie requesta.
Proszę o przeniesienie walidacji do dedykowanego walidatora.

2021-03-29 10:00 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/dto/UserDTO.java
> +@Builder
W przypadku wykorzystania obiektu jako kontenera na dane otrzymane w requestcie "Builder" nie jest konieczny.

2021-03-29 10:00 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/model/User.java
> +    public enum Status {
Enumy "Status" i "Role" powinny zostać przeniesione poza klasę User.

2021-03-29 10:00 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/model/User.java
> +@Data
Umieszczenie klasy User w aktualnym package'u wskazuje że będzie ona wykorzystywana na potrzeby logiki biznesowej aplikacji. Jeśli tak, wówczas adnotacja "Data" jest nadmiarowa.

2021-03-29 10:00 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/exception/UserControllerValidationHandlerAdvice.java
> +public class UserControllerValidationHandlerAdvice {
Ze względu na specyfikę realizowanej aplikacji oraz sposób działania "ControllerAdvice", walidacja danych np.: otrzymanych w request'cie, powinna zostać zrealizowana przy pomocy dedykowanego mechanizmu walidacji (oddelegowanego do osobnej klasy, opracowanego mechanizmu walidatora, etc. - wszelkie propozycje mile widziane :)). ControllerAdvice'ory powinniśmy zostawić na zrealizowanie ogólnego, wspólnego dla całej aplikacji sposobu obsługi komunikatów błędów biznesowych jak i odpowiedniego ich logowania.
Ponieważ temat jest ciekawy i może wymagać dodatkowych doprecyzowań, zdecydowanie nie zmieści się w komentarzu :). Zachęcam do kontaktu na Slacku. Temat jest ciekawy, ponieważ dobrze opracowana architektura rozwiązania może stanowić podwaliny mechanizmu wykorzystywanego na dalszych etapach prac.

2021-03-29 10:00 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/exception/UserControllerValidationHandlerAdvice.java
> +public class UserControllerValidationHandlerAdvice {
Nazwa klasy jest poprawna, ponieważ zawiera kontekst jej użycia.

2021-03-29 10:00 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/exception/UserControllerValidationHandlerAdvice.java
> +package com.intive.patronative.exception;
Proszę o zmianę nazwy pakietu. Utworzona klasa nie jest wyjątkiem :).

2021-03-30 18:15 UTC, P-Brzezinski commented on src/main/java/com/intive/patronative/dto/UserDTO.java
> +@Builder
Adnotacja @Builder skasowana

2021-03-30 18:17 UTC, P-Brzezinski commented on src/main/java/com/intive/patronative/model/User.java
> +    public enum Status {
Enumy Status i Role po mergu z deva przeniesione poza klasę User do pakietu model/profile

2021-03-30 18:18 UTC, P-Brzezinski commented on src/main/java/com/intive/patronative/model/User.java
> +@Data
Adnotacja @Data zamieniona na @Value

2021-03-30 18:21 UTC, P-Brzezinski commented on src/main/java/com/intive/patronative/model/User.java
> +@Data
Klasa User po mergu z dev przeniosiona do pakietu /model/profile

2021-04-01 17:10 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/exception/UserControllerValidationHandlerAdvice.java
> +package com.intive.patronative.exception;
proponuje nazwę pakietu validation

2021-04-01 19:10 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/dto/UserDTO.java
> +public class UserDTO {
może coś takiego https://www.baeldung.com/spring-data-rest-validators ?

2021-04-02 06:55 UTC, P-Brzezinski commented on src/main/java/com/intive/patronative/exception/UserControllerValidationHandlerAdvice.java
> +package com.intive.patronative.exception;
Nazwa pakietu zamieniona na validaton

2021-04-02 06:56 UTC, P-Brzezinski commented on src/main/java/com/intive/patronative/dto/UserDTO.java
> +public class UserDTO {
Jako tymczasowe rozwiązanie dopóki Zespół nie ustali wspólnego sposobu walidacji, obecny sposób pozostaje (uzgodnione z Liderem)

2021-04-02 06:56 UTC, P-Brzezinski commented on src/main/java/com/intive/patronative/exception/UserControllerValidationHandlerAdvice.java
> +public class UserControllerValidationHandlerAdvice {
Wspólny sposób walidacji zostanie ustalony podczas sprintu nr 2

2021-04-05 18:34 UTC, kari565 commented on src/main/java/com/intive/patronative/service/UserService.java
> +import com.intive.patronative.model.dto.UserDTO;
W devie nie ma folderu model. Jest za to folder dto.

2021-04-05 18:34 UTC, kari565 commented on src/main/java/com/intive/patronative/validation/UserControllerValidationHandlerAdvice.java
> +    @AllArgsConstructor
Tutaj zamiast @Data i @AllArgsConstructor można dać @Value. Wtedy trzeba usunąć modyfikator private z pól w ViolationError.

2021-04-05 18:34 UTC, kari565 commented on src/main/java/com/intive/patronative/validation/UserControllerValidationHandlerAdvice.java
> +    @Data
Tutaj adnotację @DaTa można zastąpić adnotacją @value.

2021-04-05 21:00 UTC, kari565 commented on src/main/java/com/intive/patronative/validation/UserControllerValidationHandlerAdvice.java
> +        for (FieldError fieldError : e.getBindingResult().getFieldErrors()) {
Moża zmienić:
ValidationErrorResponse error   ->   final var error
FieldError fieldError   ->   final var fieldError

2021-04-06 20:46 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/controller/UserController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body("User saved");
body jest tu chyba nadmiarowe jeżeli nie zwraca żadnej referencji (id / url)

2021-04-07 13:02 UTC, P-Brzezinski commented on src/main/java/com/intive/patronative/controller/UserController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body("User saved");
Zwraca komunikat ale pewnie późnej będzie to zmienione na coś lepszego. Zmienię na void.

2021-04-07 13:16 UTC, P-Brzezinski commented on src/main/java/com/intive/patronative/service/UserService.java
> +import com.intive.patronative.model.dto.UserDTO;
Zmieniłem model na dto, UserDTO przeniosłem do dto/model

2021-04-07 13:17 UTC, P-Brzezinski commented on src/main/java/com/intive/patronative/validation/UserControllerValidationHandlerAdvice.java
> +    @Data
Zamienione :)

2021-04-07 13:17 UTC, P-Brzezinski commented on src/main/java/com/intive/patronative/validation/UserControllerValidationHandlerAdvice.java
> +        for (FieldError fieldError : e.getBindingResult().getFieldErrors()) {
Zamienione :)

2021-04-07 13:18 UTC, P-Brzezinski commented on src/main/java/com/intive/patronative/controller/UserController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body("User saved");
Zwraca HTTP status i komunikat, jeżeli ma być inaczej proszę o propozycję

2021-04-07 13:18 UTC, P-Brzezinski commented on src/main/java/com/intive/patronative/validation/UserControllerValidationHandlerAdvice.java
> +    @AllArgsConstructor
Zamienione :)

2021-04-07 13:43 UTC, kari565 approved these changes

2021-04-08 09:29 UTC, patronage-java-leaders-2021 approved these changes
Zerknij proszę na komenatrze i wprowadź drobne poprawki. Następnie rozwiąż konflikty z dev'em, zrób squasha i dodaj zmiany do dev'a.
Dzięki.

2021-04-08 09:29 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/validation/UserControllerValidationHandlerAdvice.java
> +    ValidationErrorResponse onMethodArgumentNotValidException(MethodArgumentNotValidException e){
Postaraj się używać bardziej znaczących, opisowych nazw - nazwa parametru "e" nie mówi nic o niej. Proponuję abyś użył np.: validationException albo innej nazwy która jest samoopisująca się.

2021-04-08 09:29 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/validation/UserControllerValidationHandlerAdvice.java
> +
Usuń proszę nadmiarową pustą linię

2021-04-08 17:36 UTC, lzolkiewski approved these changes

2021-04-10 09:35 UTC, barbara-tyndorf approved these changes

2021-04-11 12:40 UTC, merged