Wip ip2 198
intive/patronage21-java pull request #18
Opened 2021-04-01 08:22 UTC by lzolkiewski

2021-04-01 14:13 UTC, patronage-java-leaders-2021 requested changes
Zmień proszę brancha docelowego na "dev". A przy okazji zweryfikuj także .gitignore'a - "trochę" za dużo plików do dodania do repo :).
Dzięki.

2021-04-01 19:47 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/controller/GroupController.java
> +        Groups groups = groupService.getGroups();
a jakby dał var? Już widziałem ktoś w testach w PR używał.

2021-04-01 19:47 UTC, KrzysztofPawlak commented on src/test/java/com/intive/patronative/controller/GroupControllerTest.java
> +    @Order(1)
a jest jakaś specyficzna potrzeba tego Order?

2021-04-02 09:01 UTC, lzolkiewski commented on src/test/java/com/intive/patronative/controller/GroupControllerTest.java
> +    @Order(1)
Obecnie rzeczywiście nie ma

2021-04-02 09:07 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/controller/GroupController.java
> +        Groups groups = groupService.getGroups();
Z tego co widzę zależy od preferencji stosowanie go lub nie.

2021-04-02 13:38 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/controller/GroupController.java
> +        Groups groups = groupService.getGroups();
Proponuję używać "var" tam, gdzie czytelność kodu nie ucierpi na tym. Zatem dla osoby czytającej kod, typ będzie łatwy do ustalenia bez "zagłębiania się" w kod, a i nazwa zmiennej będzie jednoznacznie wskazywała na możliwy typ danych.
Tutaj również powinien być "final" :).

2021-04-02 14:37 UTC, patronage-java-leaders-2021 requested changes

2021-04-02 14:37 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/controller/ApiUserController.java
> +    public void updateUser(@Valid @RequestBody User userDTO) {
Dodaj proszę "final" do parametru metody.

2021-04-02 14:37 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/UserService.java
> +    public void update(User userDTO) {
Dodaj proszę "final" do parametru metody.

2021-04-02 14:37 UTC, patronage-java-leaders-2021 commented on src/test/java/com/intive/patronative/controller/GroupControllerTest.java
> +    public void groups() throws Exception {
Nazwy metod testujących powinny wskazywać na test case któremu służą. W tym przypadku powinieneś utworzyć osobne metody testowe które zrealizują weryfikację przypadków testowych. Możemy przyjąć że metoda powinna zaczynać się od słowa "should". Zatem, w tym przypadku powinieneś mieć metody: "should_provide_all_groups", "should_provide_selected_groups_only" i "should_return_no_groups". Metoda testująca powinna składać się z 3 części: given, when i then. W razie pytań lub wątpliwości, zapraszam do kontaktu.

2021-04-02 14:37 UTC, patronage-java-leaders-2021 commented on src/test/java/com/intive/patronative/service/GroupServiceTest.java
> +    public void getGroups_shouldReturnGroupsFromRepository() {
W przypadku weryfikacji poprawności działania warstwy serwisowej, zrealizuj proszę testy wykorzystując testy parametryczne, żeby sprawdzić możliwe scenariusze. Wówczas powstanie jedna metoda która przyjmuje parametry testowe i wykorzytuje je na etapie weryfikacji logiki. Parametry przekazywane są przy pomocy adnotacji "Parameters" i nazwa metody w której przygotowujesz dane testowe. W razie pytań lub wątpliwości, zapraszam do kontaktu.

2021-04-05 15:12 UTC, kari565 commented on src/main/java/com/intive/patronative/controller/api/GroupController.java
> +        }
groups.getGroups() == null - getGroups() nigdy nie zwróci nulla, tylko pustą listę.

Tutaj mogła by zostać zwrócona pusta lista i status HTTP OK. Według tej strony https://coderwall.com/p/gbxelq/simple-rules-for-a-sane-restful-api-design: Empty arrays shall not be null. If a field is some kind of list and it is represented by an array, an array shall be returned, even if empty.

2021-04-05 15:12 UTC, kari565 commented on src/test/java/com/intive/patronative/controller/GroupControllerTest.java
> +    public void groups_should_return_all_groups_and_ok_status(Groups groups) throws Exception {
Tutaj nazwy metod testowych zostały napisane przy użyciu snake case'a, natomiast w GroupSrviceTest.java przy użyciu camel case'a. Teraz jest niespójnie.

2021-04-06 08:58 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/controller/api/GroupController.java
> +        }
Widziałem spory ludzi przy używaniu OK, NoContent i Not_Found. 
Uznałem że w momencie gdy nie mamy co zwracać najlepiej nie zwracać nic i zostawić to frontend'owi do obsługi chociaż OK z pustą listą też nie jest złe. Na razie zostanę przy noContent, przydało by się jako zespół ustalić jak to obsługiwać wtedy można by zwracać w takich przypadkach jeden status.
Co do null'a jest to zrobione bardziej na przyszłość gdy będzie w aplikacji baza danych na wszelki wypadek w przyszłości można to zmienić na razie przynajmniej do momentu dodania bazy danych zostawiłbym to w ten sposób.

2021-04-06 14:39 UTC, closed without merging