IP2-213 - add schema.sql
intive/patronage21-java pull request #22
Opened 2021-04-07 22:11 UTC by kari565

2021-04-08 08:50 UTC, patronage-java-leaders-2021 requested changes
Przed dalszymi zmianami w SQL'u, proponuję aby najpierw zbudować końcowy model w UML'u bazy danych i następnie przenieść go do SQL'a.

2021-04-08 08:50 UTC, patronage-java-leaders-2021 commented on src/main/resources/schema.sql
> +  id              SERIAL PRIMARY KEY,
W przypadku klucza głównego proponuję definiować go jako NUMERIC(19, 0). Generowanie wartości dla klucza głównego (który jest sztuczny), możemy zrealizować definiując na bazie danych sekwencje, np.:
create sequence member_seq increment by 10 minvalue 1 maxvalue 999999999999999999 cache 10 no cycle;
Możemy również polegać na wartościach które dostarczy nam Hibernate, lecz zaproponowane podejście w którym wykorzystujemy sekwencje jest bliższe "produkcyjnemu", i do zastosowania takiego podejścia zachęcam :).
W razie pytań lub wątpliwości, zapraszam do kontaktu.

2021-04-08 08:50 UTC, patronage-java-leaders-2021 commented on src/main/resources/schema.sql
> +  bio           VARCHAR(255),
W przypadku bio proponuję zrobić więcej "miejsca", np.: 256 lub nawet 512 znaków.

2021-04-16 13:32 UTC, lzolkiewski approved these changes

2021-04-18 09:05 UTC, KrzysztofPawlak commented on src/main/resources/db.sql
> +        github_url   VARCHAR(64) NOT NULL,
przy rejestracji nie mamy podanego githuba, więc albo trzeba dać jakąś dummy wartość, albo ściągnąć tego nulla

2021-04-20 06:59 UTC, patronage-java-leaders-2021 commented on src/main/resources/db.sql
> +        github_url   VARCHAR(64) NOT NULL,
@kari565 : proszę o poprawkę zgodnie z sugestią @KrzysztofPawlak.
Dodatkowo proponuję aby pole github_url było dłuższe, np.: 255 znaków.

2021-04-20 07:34 UTC, patronage-java-leaders-2021 requested changes

2021-04-20 07:34 UTC, patronage-java-leaders-2021 commented on src/main/resources/db.sql
> +        description VARCHAR(256) NOT NULL,
Proponuję aby zrobić  pole 'description'jako opcjonalne. Proszę o zmianę.

2021-04-20 07:34 UTC, patronage-java-leaders-2021 commented on src/main/resources/db.sql
> +        description VARCHAR(256) NOT NULL
Pole 'description' proponuję zrobić jako opcjonalne. Proszę o zmianę.

2021-04-20 10:51 UTC, KrzysztofPawlak commented on src/main/resources/db.sql
> +        name VARCHAR(32) NOT NULL
w role/status/gender nie chcemy mieć unique na name?

2021-04-20 10:51 UTC, KrzysztofPawlak commented on src/main/resources/db.sql
> +        name VARCHAR(64) NOT NULL
może unique?

2021-04-20 10:51 UTC, KrzysztofPawlak commented on src/main/resources/db.sql
> +        name VARCHAR(32) NOT NULL
unique?

2021-04-20 11:25 UTC, kari565 commented on src/main/resources/db.sql
> +        name VARCHAR(32) NOT NULL
Poprawione

2021-04-20 11:26 UTC, kari565 commented on src/main/resources/db.sql
> +        name VARCHAR(64) NOT NULL
Poprawione

2021-04-20 11:26 UTC, kari565 commented on src/main/resources/db.sql
> +        name VARCHAR(32) NOT NULL
Poprawione

2021-04-20 11:26 UTC, kari565 commented on src/main/resources/db.sql
> +        github_url   VARCHAR(64) NOT NULL,
Poprawione

2021-04-20 11:26 UTC, kari565 commented on src/main/resources/db.sql
> +        description VARCHAR(256) NOT NULL,
Poprawione

2021-04-20 11:26 UTC, kari565 commented on src/main/resources/db.sql
> +        description VARCHAR(256) NOT NULL
Poprawione

2021-04-20 11:40 UTC, KrzysztofPawlak commented on src/main/resources/db.sql
> +        role_id      NUMERIC(19, 0) NOT NULL,
te 3 też chyba mogę REFERENCES

2021-04-20 18:23 UTC, kari565 commented on src/main/resources/db.sql
> +        role_id      NUMERIC(19, 0) NOT NULL,
Dodane

2021-04-21 14:45 UTC, patronage-java-leaders-2021 approved these changes

2021-04-21 15:15 UTC, KrzysztofPawlak approved these changes

2021-04-21 15:45 UTC, merged