IP2-206 - Add login field
intive/patronage21-java pull request #23
Opened 2021-04-08 10:21 UTC by lzolkiewski

2021-04-08 12:46 UTC, kari565 approved these changes

2021-04-08 15:45 UTC, KrzysztofPawlak approved these changes

2021-04-08 18:08 UTC, barbara-tyndorf approved these changes

2021-04-09 04:54 UTC, patronage-java-leaders-2021 requested changes
W tym merge requeście alarmujace jest to że mamy za dużo commit'ów jak na dodanie pola login.
Sprawdziłem lokalnie przy pomocy komendy 'gitk origin/dev origin/wip_ip2-206' jak wygląda sytuacja z synchronizacją tych 2 branchy i 5 commitów nie ma jeszcze w dev'ie. Jeżeli zadanie jest zblokowane przez inne zadanie (na przykład przez brak modelu) to trzeba ustawić je w statusie blocked. 

W tym przypadku jakbyśmy zrobili merge request'a pod spodem wpadnie też inne zadanie
![2021-04-09 06_50_12-Settings](https://user-images.githubusercontent.com/78137562/114129951-de625200-98ff-11eb-88db-3c8328721078.png)

2021-04-13 09:46 UTC, patronage-java-leaders-2021 commented
@lzolkiewski: wyrównaj proszę Twojego feature branch z dev'em, rozwiąż konflikty które się pojawią, a następnie zrób squasha swoich zmian do jednego commita. Następnie zrób pusha do feature brancha. Jak będzie gotowe daj proszę znać. W razie pytań lub wątpliwości zapraszam do kontaktu.
Ewentualnie jeśli rozwiązanie konfliktów zajmie zbyt dużo czasu, możesz zamknąć tego pull requsta, utworzyć nowego feature brancha od aktualnej wersji dev'a, przenieść swoje zmiany i wystawić nowego pull requesta. Tego wówczas zamknij.

2021-04-13 16:07 UTC, closed without merging

2021-04-13 16:21 UTC, lzolkiewski commented
Zmiany zostały przygotowane w gałęzi wip_ip2-206_fix