IP2-207 setup database using docker
intive/patronage21-java pull request #24
Opened 2021-04-08 10:46 UTC by barbara-tyndorf

2021-04-08 11:16 UTC, lzolkiewski commented on docker-compose.yml
> +  postgres:
Mogłabys dodać container_name z ładną nazwą dla bazy danych

2021-04-08 11:16 UTC, lzolkiewski commented on docker-compose.yml
> +  adminer:
Mogłabyś dodać container_name z ładną nazwą dla adminer'a

2021-04-08 11:18 UTC, lzolkiewski commented on src/main/resources/application.yml
> +    url: jdbc:postgresql://localhost:5432/patronative
Tutaj nie jestem pewien ale chyba powinnać się raczej odwoływać do kontenera z dockera
jdbc:postgresql://nazwa_kontenera:5432/patronative

2021-04-08 11:20 UTC, lzolkiewski commented on docker-compose.yml
> +    image: postgres
Tutaj mogłabyś dodać tag latest

2021-04-08 15:56 UTC, KrzysztofPawlak commented on README.md
> +- `PASSWORD`: **p4tron4tiv3**
nie wiem czy hasło w readme to dobry pomysł

2021-04-08 15:56 UTC, KrzysztofPawlak commented on docker-compose.yml
> +      POSTGRES_PASSWORD: p4tron4tiv3
nie wiem czy hasło w tym miejscu to dobry pomysł

2021-04-08 17:52 UTC, barbara-tyndorf commented on README.md
> +- `PASSWORD`: **p4tron4tiv3**
masz rację nie jest to dobry pomysł, raczej chciałam, żeby było to widoczne dla Was

2021-04-08 17:53 UTC, barbara-tyndorf commented on src/main/resources/application.yml
> +    url: jdbc:postgresql://localhost:5432/patronative
powiem tak: u mnie działa ;) ale może masz rację, poczekam na komentarz liderów

2021-04-08 17:58 UTC, barbara-tyndorf commented on docker-compose.yml
> +  postgres:
jakieś propozycje? patronative_db to będzie ładna nazwa? :)

2021-04-08 18:59 UTC, lzolkiewski commented on docker-compose.yml
> +  postgres:
Bardzo :)

2021-04-08 19:36 UTC, KrzysztofPawlak commented on README.md
> +````
ponieważ jest w detached mode myślę, że można dodać jakieś info z poleceniami jak wylistować i ubić

2021-04-09 07:58 UTC, patronage-java-leaders-2021 commented on docker-compose.yml
> +      POSTGRES_PASSWORD: p4tron4tiv3
Hasło może pozostać w pliku, ponieważ na chwilę obecną Dockerem i docker-compose będziemy posługiwać się w celach developerskich. W momencie gdy przejdziemy na Cloud'a parametry konfiguracyjne będziemy zaczytywać w inny sposób - ale wszystko po kolei :).
Hasło jest secure :).

2021-04-09 08:14 UTC, patronage-java-leaders-2021 commented on docker-compose.yml
> +  adminer:
Z kontenera 'adminer' możemy zrezygnować, ponieważ dostęp bazy danych można uzyskać na przykład przy pomocy IDE, DataGripa (tool od JetBrains), itp.

2021-04-09 08:20 UTC, patronage-java-leaders-2021 requested changes

2021-04-09 08:20 UTC, patronage-java-leaders-2021 commented on docker-compose.yml
> +      - 8085:8080
Proponuję zmiany mapowania portu docelowego. Powinno być 8085, ponieważ 8080 będzie defaultowo zajęty przez Tomcat'a. Zatem wystawienie portów powinno zostać skonfigurowane jako: 8085:8085

2021-04-09 08:20 UTC, patronage-java-leaders-2021 commented on docker-compose.yml
> +      - 8085:8080
Pliki bazy danych powinny być przechowywane w volumenie. Wprowadź proszę dla kontenera postgres volumen (np.: o nazwie pgdata, albo innej zaproponowanej przez Ciebie) który będzie podmontowany w lokalizacji /var/lib/postgresql/data w systemie plików kontenera.
Kilka informacji i wskazówek o volumenach znajdziesz tutaj: https://docs.docker.com/storage/volumes/
Jeśli będziesz miała jakieś pytania lub wątpliwości - zapraszam do kontaku :).

2021-04-09 11:06 UTC, barbara-tyndorf commented on docker-compose.yml
> +      - 8085:8080
Skoro rezygnujemy z adminera, to chyba niepotrzebna ta zmiana, bo usuwam wszystko, co go dotyczy?

2021-04-09 16:52 UTC, barbara-tyndorf commented on docker-compose.yml
> +  postgres:
done :)

2021-04-09 18:28 UTC, lzolkiewski approved these changes

2021-04-12 14:38 UTC, patronage-java-leaders-2021 approved these changes
Zerknij proszę na komentarze. Po ich naniesieniu dodaj proszę zmianę do dev'a.

2021-04-12 14:38 UTC, patronage-java-leaders-2021 commented on README.md
> +
Proponuję dodać informację o zatrzymaniu wszystkich kontenerów podniesionych przy pomocy docker-compose, należy użyć polecenia  "docker-compose down".
Podobnie wylistowanie kontenerów podniesionywch przy pomocy docker-compose możliwe jest z przy pomocy "docker-compose ps". Poniższe informacje mogą zostać jako dodatkowe wskazówki jak postępować z pojedynczymi kontenerami.

2021-04-12 20:18 UTC, merged