Wip ip2 125
intive/patronage21-java pull request #3
Opened 2021-03-22 17:33 UTC by KrzysztofPawlak

2021-03-22 19:01 UTC, lzolkiewski approved these changes
Te enumy można by wsadzić w model użytkownika. 
Mimo to jest w porządku.

2021-03-22 19:08 UTC, P-Brzezinski approved these changes

2021-03-22 19:37 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/model/User.java
> +@Data
to można zawsze później by było dodać, jak już będzie potrzeba

2021-03-23 08:26 UTC, patronage-java-leaders-2021 commented
1) Mamy 5 commit'ów dla stworzenia jednej klasy to jednak za dużo. Należy zrobić squash'a w commitach. Można do tego podejść w kilka sposobów ja osobiście korzystam z komendy w stylu "git rebase -i HEAD~10" i robię to z poziomu terminalu (używam bash'a)
2) Nazwa commit'a powinna zawierac numer zadania i wyglądać mniej więcej tak "IP2-125 - Add user model"
3) Jeżeli chodzi o adnotację w modelu zostaw póki co @Data albo @Value, w momencie kiedy będzie potrzeba wykorzystania jakiejś innnej adnotacji lombok'owej wtedy można śmiało dodać w razie potrzeby 
4) Jeżeli chodzi o pola w klasie to powinny być na samej górze a dopiero poniżej ich metody i enumy,

2021-03-24 14:03 UTC, patronage-java-leaders-2021 requested changes

2021-03-24 14:03 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/model/User.java
> +    public enum Role {
Enumy Role i Status powinny zostać przeniesione do osobnych plików, co będzie miało znaczenie na etapie realizacji warstwy utrwalania. Przenosząc je, warto również zwrócić uwagę na umieszczenie ich w odpowiednim pakiecie. 
Zaproponowane nazwy `Status`  i `Role` są ogólne i nie wskazują kontekstu użycia. Dla zachowania czytelności kodu i poprawnego użycia, proponuje wprowadzenie do nazwy Enumów dodatkowej informacji wskazującej na kontekst ich użycia, np.: `Status` -> `UserStatus`, i `Role` -> `UserRole`.
Użyte modyfikatory dostępu sugerują że wspomniane typy wyliczeniowe mogą zostać użyte w dowolnym miejscu w kodzie.

2021-03-24 14:18 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/model/User.java
> +@Data
@KrzysztofPawlak: Czy zaproponowany model dotyczy warstwy prezentacji czy warstwy utrwalania (bazy danych)?

2021-03-24 22:25 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/model/User.java
> +@Data
jako że jest już w innych PR dto i na razie jest wystarczający (obecnie nie widzę potrzeby na innego DTOsa z statusem i rolą) więc wychodzi na to że to będzie model bazy danych. Dodałem stosowne adnotacje. Bez zależności do konkretnej bazy danych

2021-03-25 07:02 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/model/User.java
> +@Data
widzę że DTOsy już znajdują się w innych PR oraz nie widzę, gdzie można by było zastosować to jako kolejny model dla widoku, wychodzi na to że jest to model dla bazy danych. Dodałem stosowne adnotacje.

2021-03-25 07:19 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/model/User.java
> +    public enum Role {
enumy zostały przeniesione do osobnych plików. Co do pakietu o czym mowa w komentarzu to myślę, że mogło chodzić o umieszczenie tego w pakiecie db lub users, jeżeli nie to proszę o wskazówkę. Co do pól publicznych to dałem to celowo ponieważ services i controllers obecnie są w osobnych pakietach (w PR).

2021-03-29 10:13 UTC, patronage-java-leaders-2021 approved these changes

2021-03-29 10:13 UTC, patronage-java-leaders-2021 approved these changes

2021-03-29 12:32 UTC, merged