Wip ip2 221
intive/patronage21-java pull request #30
Opened 2021-04-18 21:41 UTC by KrzysztofPawlak

2021-04-19 07:38 UTC, patronage-java-leaders-2021 commented
Proszę o zrobienie porządku w commitach bo pokazuje się ich tutaj całkiem sporo ;)

2021-04-19 08:54 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/dto/registration/ConsentDTO.java
> +    Boolean flag;
Brakuje ci private przy polach możesz użyć lombokowego @FieldDefaults jeżeli nie chcesz dodawać tego na wszystkich polach

2021-04-19 08:57 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/dto/registration/GroupDTO.java
> +    String name;
Podobnie jak poprzednio private lub fieldDefaults by się przydało

2021-04-19 09:05 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/dto/registration/UserRegistrationReadDTO.java
> +    List<ConsentDTO> consents = new ArrayList<>();
Przydał by sie @FieldDefaults lub private chyba, że jest jakiś cel dla którego wszystkie zostawiłeś w taki sposób

2021-04-19 09:06 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/dto/registration/UserRegistrationWriteDTO.java
> +    List<ConsentDTO> consents = new ArrayList<>();
Przydał by się @FieldDefaults lub private chyba, że jest jakiś cel dla którego wszystkie zostawiłeś w taki sposób

2021-04-19 09:20 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/service/ConsentService.java
> +        }
Mógłbyś to wyrzucić do osobnej funkcji i nadać temu jakąś nazwę co to dokładnie robi, zmniejszyło by to nieco tą funkcję i trochę dodało jasności

2021-04-19 09:23 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/service/ConsentService.java
> +                .collect(Collectors.toSet());
Dla przejrzystości można by to wyrzucić do oddzielnej funkcji powiedzmy getNotRequiredConsents(fetchedConsents)

2021-04-19 09:25 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/service/ConsentService.java
> +                .collect(partitioningBy(Consent::isRequired, Collectors.toSet()));
Możesz stworzyć funkcję getConsents, zmniejszy to ilość linii w tej funkcji i zwiększy przejrzystość

2021-04-19 09:28 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/service/TechnologyGroupService.java
> +                .collect(Collectors.toSet());
Możesz dodać FormGroups(technologyGroups)

2021-04-19 09:30 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/service/TechnologyGroupService.java
> +                .collect(Collectors.toSet());
To też można by zamienić na funkcję

2021-04-19 09:31 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/service/TechnologyGroupService.java
> +        if (technologyGroups.size() != filteredTechnologyGroups.size() || filteredTechnologyGroups.isEmpty()) {
Mógłbyś zamknąć to sprawdzenie czy są różne w nawias

2021-04-19 10:18 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/service/UserService.java
> +        return userMapper.toUserRegistrationDto(userRepository.save(userToSave));
Przy tworzeniu użytkownika raczej nie powinieneś zwracać użytkownika, a jedynie status

2021-04-19 10:22 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/service/UserService.java
> +        userToSave.setConsents(consentsToAssignToUser);
Mógłbyś to zamknąć w prywatnej funkcji powiedzmy createUser i zwracać gotowego użytkownika do zapisu

2021-04-19 10:29 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/controller/api/UserController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(savedUser);
można by ustalić czy powinniśmy zwracać zawartość po tworzeniu użytkownika

2021-05-04 09:10 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/dto/registration/UserRegistrationWriteDTO.java
> +@Data
wszędzie to raczej nie bo, część jest potem mapowana, a nie wszędzie jest builder

2021-05-04 11:10 UTC, patronage-java-leaders-2021 requested changes

2021-05-04 11:10 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/UserService.java
> +    private Role getRole() {
Jeśli metoda ma być reużywalna, powinna przyjmować jako parametr rolę.  Aktualnie nazwa metody nie wskazuje również na rolę która jest przyjęta jako kryterium wyszkiwania. Proszę o poprawkę.

2021-05-04 11:10 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/UserService.java
> +    private Status getStatus() {
Sytuacja analogiczna do metody `getRole` - proszę o poprawę.

2021-05-04 11:10 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/UserService.java
> +    private Gender getGender(final UserRegistrationWriteDTO userRegistrationForm) {
Proszę o przekazanie do metody parametru będącego kryterium wyszukiwania zamiast całego obiektu który nie jest wykorzystywany.

2021-05-04 11:10 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/UserService.java
> +        final var userToSave = userMapper.toUserRegistrationEntity(userRegistrationForm);
Proszę o przeniesienie funkcjonalności mapowania do osobnej dedykowanej metody i wywołanie jej w tym miejscu.

2021-05-04 11:10 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/ConsentExtractor.java
> +public class ConsentExtractor {
Jaki jest cel biznesowy/przeznaczenie tej klasy?

2021-05-04 11:19 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/dto/registration/ConsentDTO.java
> +@EqualsAndHashCode(onlyExplicitlyIncluded = true)
tu chodzi o to że w UserRegistrationWriteDTO mam na liście adnotacje @UniqueElements przez co nie można będzie przekazać 2 consent o tej samej treści. Flaga wtedy nie ma znaczenia

2021-05-04 11:29 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/service/ConsentExtractor.java
> +public class ConsentExtractor {
przychodzi lista DTO z zgodami, zwracana jest lista z modelami (DB) do zapisu przy rejestracji. 
Klasa sprawdza czy wszystkie pobrane z bazy wymagane zgody znajdują się w przekazanej liście DTO i czy są one potwierdzone. Jeżeli jest ok, to zgoda jest usunięta z listy DTO.
Dla pozostałych zgód przekazanych w DTO, sprawdzane jest czy występuje taka zgoda na liście Zgód (DB), jak nie ma to wyjątek, jeżeli jest i jest potwierdzona (flag = true) to obiekt zgody (DB) jest dodawany do listy wyjściowej.
Zgoda nie potwierdzona i nie wymagana nie jest zapisywana.
Brakuje mi lepszej nazwy, proszę o sugestie.

2021-05-04 19:39 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/dto/profile/UserDTO.java
> +public class UserDTO {
to zostawię na razie bez zmian żeby się nie zastanawiać, ten PR tego nie wykorzystuje

2021-05-04 19:40 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/dto/registration/UserRegistrationWriteDTO.java
> +@Data
będzie inaczej, bo to nie takie proste pogodzić @Value z Jaksonem

2021-05-08 16:19 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/dto/registration/TechnologyGroupDTO.java
> +@AllArgsConstructor
W value masz AllArgsConstructor już zawarty, NoArgsConstructor też raczej nie jest ci tu potrzebne gdy masz Value

2021-05-08 16:21 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/dto/registration/ConsentDTO.java
> +@Getter
To mógłbyś zamienić po prostu adnotacją Value

2021-05-08 16:23 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/dto/registration/UserRegistrationRequestDTO.java
> +@AllArgsConstructor
Samo Value powinno wystarczyć

2021-05-08 18:44 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/dto/registration/ConsentDTO.java
> +@Getter
Value generujesz equals i hashcode na wszystkie pola, a tego nie chce

2021-05-08 18:49 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/dto/registration/TechnologyGroupDTO.java
> +@AllArgsConstructor
to jest rozwiazanie aby otrzymać: Immutable + Lombok + Jackson

2021-05-14 06:19 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/controller/api/UserController.java
> +        return ResponseEntity.status(response.isSuccess() ? CREATED : OK).body(response);
Obydwa statusy CREATED i OK są success, ale ogólnie jeżeli mamy POST to możemy ustalić, ze zwracamy 204, jeżeli coś się wywali po drodze to powinniśmy rzucić błędem

2021-05-14 06:24 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/UserService.java
> +            return UserRegistrationResponseDTO
Jeżeli tutaj jest jakiś błąd który nie pozwoli nam założyć użytkownika (a to chcemy zrobic według operacji http) to powinniśmy rzucić po prostu błędem, że jest to niemożliwe i dlaczego.

2021-05-14 06:27 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/validation/ConsentValidation.java
> +public class ConsentValidation {
Nie bardzo rozumiem, dlaczego ta klasa powstała i robi tyle rzeczy na raz, pownineneś zrobić coś podobnego do UserSerachValidator gdzie przejdziesz przez wszsytkie przypadki zbierzesz ewentualne problemy z requestem i rzucisz błędem

2021-05-14 06:33 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/UserService.java
> +        final var candidateRole = getRoleByName(UserRole.CANDIDATE);
Wyciągamy Role żeby przypisać taką samą role, niepotrzebny strzał do bazy

2021-05-14 06:33 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/UserService.java
> +        final var initialStatus = getStatusByName(UserStatus.ACTIVE);
Tutaj też niepotrzebny strzał do bazy

2021-05-14 06:34 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/UserService.java
> +        final var gender = getGenderByName(userRegistrationRequestDTO.getGender());
To samo co wyżej strzał do bazy :)

2021-05-14 06:36 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/UserService.java
> +
Tutaj można wyrzucić wszystko do osobnej metody która jest odpowiedzialna za walidację requesta i rzuceniem błędu

2021-05-14 06:36 UTC, patronage-java-leaders-2021 requested changes
Trzeba uprościć kod

2021-05-14 09:33 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/validation/ConsentValidation.java
> +public class ConsentValidation {
z tego co pytałem i jak to zrozumiałem to to nie jest sytuacja wyjątkowa, więc tamto zachowanie w UserSearchValidator nie jest do końca ok.

2021-05-14 09:43 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/service/UserService.java
> +        final var candidateRole = getRoleByName(UserRole.CANDIDATE);
rozumiem że to o te enumerated chodzi

2021-05-18 06:26 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/service/UserService.java
> +        final var candidateRole = getRoleByName(UserRole.CANDIDATE);
może się mylę, ale przy obecnym modelu się nie da? Sprawdziłem wstępnie - nie działało i nie chciałem w to brnąc, bo było wiele innych rzeczy do poprawy.

2021-05-19 14:14 UTC, patronage-java-leaders-2021 requested changes

2021-05-19 14:14 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/validation/TechnologyGroupsValidator.java
> +    private static final int TECHNOLOGY_GROUP_LENGTH = 20;
Ograniczenia na długość nazwy grupy powinny odpowiadać temu co jest w bazie danych. Proszę o weryfikację i dostosowanie.
Proszę również o zmianę na bardziej jednoznaczne i samoopisujące się nazwy stałych:
- TECHNOLOGY_GROUP_LENGTH
- TECHNOLOGY_GROUP_MIN_SIZE,
- TECHNOLOGY_GROUP_MAX_SIZE.

Aktualnie, bez przejrzenia kodu trudno jest ustalić ich przeznaczenie.

2021-05-19 14:14 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/validation/UserValidator.java
> +        return (firstName == null && !isRequired) || (isFirstNameValid(firstName))
Spradzenie wymagalności na polu (isRequired) powinno odbywać się zanim jakiekolwiek inne sprawdzenie zostanie wykonane. 
Zatem isRequired && !isFirstNameValid -> getFieldError(); else -> null. 
Przełoży się to na znaczną poprawę czytelności kodu i uprościć implementację. Proszę rozpropagować zmianę tam gdzie to możliwe w pozostałych metodach klasy.

2021-05-19 18:36 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/mapper/GroupMapper.java
> +        return new TechnologyGroupDTO(technologyGroup.getName());
Można by to zamienić na coś takiego
`return Optional.ofNullable(technologyGroup).map(group -> new TechnologyGroupDTO(group.getName())).orElse(null);`

2021-05-19 18:37 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/mapper/GroupMapper.java
> +                .collect(Collectors.toList());
Tutaj podobnie można by to ograć `Optional.ofNullable().map().orElse()`

2021-05-19 18:55 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/mapper/GroupMapper.java
> +                .collect(Collectors.toList());
tak wiem, jeszcze nie dotarłem, do tego PR-a. Wczoraj już były takie tipy

2021-05-19 19:00 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/service/GroupService.java
> +                        .orElseThrow(() -> InvalidArgumentException.valueDoesNotExists("group", technologyGroup.getName())))
to tylko kolejny sposób tworzenia i po nazwie metody wiem co mniej więcej tam będzie.

2021-05-19 21:11 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/mapper/UserMapper.java
> +                .build();
Mógłbyś to zamknąć w `Optional.ofNullable(...).map(...).orElse(...);`

2021-05-19 21:13 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/service/UserService.java
> +                createUser(userRegistrationRequestDTO);
To mogłoby być w jednej linii

2021-05-19 21:24 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/service/UserService.java
> +                createUser(userRegistrationRequestDTO);
aha no tak bo teraz nie ma tego argumentu z zgodami ;d

2021-05-19 23:39 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/validation/UserValidator.java
> +        return (firstName == null && !isRequired) || (isFirstNameValid(firstName))
Może się mylę, ale to nie zadziała. Ta metoda jest wspólna dla edycji i tworzenia użytkownika. Więc required nie powinno decydować czy ma nastąpić walidacja. obecnie isFirstNameValid() odrzuca nulle, więc przy edycji taki null to jest sytuacja ok, a tu zostanie odrzucony.
Inaczej required w obu przypadkach true/false powinien przepuszczać i sprawdzać czy jest null. Stad jest na początku bo on decyduje o reszcie.
Sprawdziłem ten podany wcześniej warunek i nie działał poprawnie.

2021-05-21 09:15 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/validation/UserValidator.java
> +        return (firstName == null && !isRequired) || (isFirstNameValid(firstName))
Kod który podałem był skrótowym zapisem algorytmu działania a nie implementacją :). Wynika on z tego jak się czyta taką metodę. Nazwa parametru metody `isRequired` jasno wskazuje, że sprawdzenie poprawności imienia może być włączone lub wyłączone (wymagalność jest zmienną). Zatem nie zaglądając do ciała metody powyższy kod czyta się jako:  "wymaganie aby imię było poprawne jest parametryzowalne". Zatem taka logika powinna zostać zapisana jak w moim poprzednim komenatrzu :).

2021-05-21 09:23 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/validation/TechnologyGroupsValidator.java
> +    private static final int TECHNOLOGY_GROUP_MAX_NUMBER_OF_PARTICIPATION = 3;
To możesz wyrzucić do pliku konfiguracyjnego, to chyba może ulec zmianie w przyszłości

2021-05-21 09:43 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/service/UserService.java
> +                technologyGroupsToAssignToUser);
mógłbyś stworzyć w tej metodzie Użytkownika przypisać mu role status płeć i grupy,
do mapera przekazać jedynie użytkownika i rejestracyjneDTO zmniejszy ci się ilość argumentów i uprości mapper

2021-05-21 09:53 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/service/UserService.java
> +        return userMapper.toUserRegistrationResponse(userRepository.save(userToSave));
przydałoby się żebyś stworzył jeszcze tutaj profil użytkownika po utworzeniu samego użytkownika

2021-05-24 09:14 UTC, lzolkiewski approved these changes
Dodaj jeszcze ten endpoint do user-front-controller

2021-05-24 14:04 UTC, KrzysztofPawlak commented
nie ma potrzeby, endpoint będzie służył do integracji z innym modułem.

2021-05-25 07:19 UTC, patronage-java-leaders-2021 requested changes

2021-05-25 13:53 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/dto/registration/UserRegistrationRequestDTO.java
> +    Set<TechnologyGroupDTO> groups = new HashSet<>();
jasne, to pozostałość z poprzedniego podejścia na adnotacjach gdzie użyłem @UniqueElements z czego potem zrezygnowałem, bo Set załatwia unikalość

2021-05-25 13:54 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/exception/InvalidArgumentException.java
> +    public static InvalidArgumentException valueDoesNotExists(final String fieldName, final String rejectedValue) {
ok, wcześniej tego nie było tam

2021-06-01 16:02 UTC, patronage-java-leaders-2021 requested changes
Proszę o aktualizację brancha o dev'a i rozwiązanie wszystkich konfliktów.

2021-06-01 16:43 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/controller/api/UserController.java
> +        final var response = userService.saveUser(userRegistrationRequestDTO);
w serwisie jest to zwracane, więc odpowiedź nie jest pusta. Lokalnie działa to prawidłowo.

2021-06-09 13:53 UTC, patronage-java-leaders-2021 requested changes

2021-06-09 13:53 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/mapper/GroupMapper.java
> +        return Optional.of(technologyGroupEntity)
W przypadku gdy technologyGroupEntity będzie nullem, Optional.of() skończy się od razu NPE. Więc jeśli chciałbyś tego uniknąć i zrealizować mapowanie tylko gdy technologyGroupEntity, wówczas powinno być Optional.ofNullable(). Proszę o poprawę.

2021-06-09 13:53 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/mapper/GroupMapper.java
> +        return Optional.of(technologyGroupsEntities)
Problem analogiczny jak powyżej. Proszę o poprawę.

2021-06-09 13:53 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/GroupService.java
> +        return Optional.of(technologyGroupsRequest)
W przypadku gdy technologyGroupsRequest będzie nullem, wówczas Optional.of() zakończy się NPE. Proszę o poprawę.

2021-06-09 13:53 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/UserService.java
> +        final var profileSaved = profileRepository.save(Profile.builder().user_id(userSaved.getId()).build());
Przy okazji wprowadzania zmian, proszę również o drobny refactor: zastąp proszę "user_id" na "userId" w obiekcie Profile. Ponieważ jest do drobna zmiana, zrealizuj ją proszę w ramach zadania. Dziękuję :).

2021-06-09 13:53 UTC, patronage-java-leaders-2021 commented on src/test/java/com/intive/patronative/controller/api/UserControllerTest.java
> +        lenient().when(userService.saveUser(UserProviderTestData.getUserDTO()))
Z jakiej przyczyny zrezygnowałeś z podejścia "strict stubbing" a wprowadziłeś "lenient" - co przekłada się na brak zweryfikowania np.: czy MOCKi są poprawnie używane?

2021-06-10 15:20 UTC, patronage-java-leaders-2021 approved these changes

2021-06-10 15:36 UTC, merged