IP-218 - add entities
intive/patronage21-java pull request #32
Opened 2021-04-21 16:15 UTC by kari565

2021-04-21 18:06 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/repository/model/Gender.java
> +    @Column(name = "name", nullable = false)
Możesz dodać tutaj length

2021-04-21 18:08 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/repository/model/Profile.java
> +    @Column(name = "bio")
Tutaj chyba musisz dać atrybut length, ponieważ domyślna to 255

2021-04-21 18:16 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/repository/model/Project.java
> +    @Column(name = "name", nullable = false)
Atrybut length można dodać

2021-04-21 18:18 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/repository/model/ProjectRole.java
> +    @Column(name = "name", nullable = false)
Atrybut length można dodać

2021-04-21 18:19 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/repository/model/Role.java
> +    @Column(name = "name", nullable = false)
Można by dodać atrybut length

2021-04-21 18:20 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/repository/model/Role.java
> +    @Column(name = "name", nullable = false)
Można by dodać atrybut length

2021-04-21 18:20 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/repository/model/Status.java
> +    @Column(name = "name", nullable = false)
Można by dodać atrybut length

2021-04-21 18:21 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/repository/model/Technology.java
> +    @Column(name = "name", nullable = false)
Można by dodać atrybut length

2021-04-21 18:22 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/repository/model/TechnologyGroup.java
> +    @Column(name = "name", nullable = false)
Można by dodać atrybut length

2021-04-21 18:25 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/repository/model/User.java
> +    private String gitHubUrl;
Można by dodać atrubyt length

2021-04-22 08:53 UTC, barbara-tyndorf commented on src/main/java/com/intive/patronative/repository/model/Gender.java
> +@Setter
Zamiast @Getter i @Setter dałabym @Data

2021-04-22 16:30 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/repository/model/TechnologyGroup.java
> +            joinColumns = @JoinColumn(name = "technology_group_id"),
Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [technology_group_id] in table [`patronative`.`group_technology`]; found [int4 (Types#INTEGER)], but expecting [numeric(19, 2) (Types#NUMERIC)]

2021-04-22 20:38 UTC, kari565 commented on src/main/java/com/intive/patronative/repository/model/TechnologyGroup.java
> +            joinColumns = @JoinColumn(name = "technology_group_id"),
Wydaje mi się, że to jest błąd przez to, że masz w tabeli group_technology pole technology_group_id typu INTEGER. W pliku db.sql, który jest w devie typ tego pola to NUMERIC(19,0). Sprawdź jakiego typu jest to pole w tej tabeli u Ciebie, bo powinno być NUMERIC(19,0).

2021-04-22 20:56 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/repository/model/TechnologyGroup.java
> +            joinColumns = @JoinColumn(name = "technology_group_id"),
tak wygląda sql
technology_group_id NUMERIC(19, 0) REFERENCES technology_group (id),
test zrobiłem tak. Zresetowałem lokalnego dev-a do stanu obecnego HARD, dodałem zmianę z tego brancha.

2021-04-22 21:50 UTC, kari565 commented on src/main/java/com/intive/patronative/repository/model/TechnologyGroup.java
> +            joinColumns = @JoinColumn(name = "technology_group_id"),
A możesz jeszcze sprawdzic w db navigatorze w Intelliju jaki masz typ tego pola?

2021-04-22 22:12 UTC, kari565 commented on src/main/java/com/intive/patronative/repository/model/Gender.java
> +    @Column(name = "name", nullable = false)
Dodane wszędzie

2021-04-22 22:17 UTC, kari565 commented on src/main/java/com/intive/patronative/repository/model/Gender.java
> +@Setter
Właśnie zastanawiam się czy mogę tu wykorzystać Lombokowe @ToString i @EqualsAndHashCode czy powinnam sama nadpisać te metody. Czytałam, że wariant Lombokowy nie sprawdza się tak dobrze w przypadku encji.

2021-04-23 08:38 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/repository/model/TechnologyGroup.java
> +            joinColumns = @JoinColumn(name = "technology_group_id"),
ok, uruchamia się. Musiałem dać dropa w kontenerze

2021-04-23 10:28 UTC, KrzysztofPawlak approved these changes

2021-04-23 12:51 UTC, lzolkiewski approved these changes

2021-04-27 11:14 UTC, patronage-java-leaders-2021 requested changes

2021-04-27 11:14 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/repository/model/Gender.java
> +@Entity
Proszę o zmianę analogiczne jak w klasie Consent.

2021-04-27 11:14 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/repository/model/Project.java
> +public class Project {
Proszę o zmiany analogiczne jak w klasie Consent.

2021-04-27 11:14 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/repository/model/ProjectRole.java
> +    @SequenceGenerator(name = "project_role_generator", sequenceName = "project_role_seq",
W SQL'u zadeklarowano że sekwencja będzie miała zaalokowane 10 itemów. Zatem w mapowaniu powinniśmy również poinformować Hibernate'a że sekwencja ma alokację na 10 itemów. Proszę o zmianę.

2021-04-27 11:14 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/repository/model/Role.java
> +    @SequenceGenerator(name = "role_generator", sequenceName = "role_seq",
W SQL'u zadeklarowano że sekwencja będzie miała zaalokowane 10 itemów. Zatem w mapowaniu powinniśmy również poinformować Hibernate'a że sekwencja ma alokację na 10 itemów. Proszę o zmianę.

2021-04-27 11:14 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/repository/model/Status.java
> +    @SequenceGenerator(name = "status_generator", sequenceName = "status_seq",
W SQL'u zadeklarowano że sekwencja będzie miała zaalokowane 10 itemów. Zatem w mapowaniu powinniśmy również poinformować Hibernate'a że sekwencja ma alokację na 10 itemów. Proszę o zmianę.

2021-04-27 11:14 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/repository/model/Technology.java
> +    @SequenceGenerator(name = "technology_generator", sequenceName = "technology_seq",
W SQL'u zadeklarowano że sekwencja będzie miała zaalokowane 10 itemów. Zatem w mapowaniu powinniśmy również poinformować Hibernate'a że sekwencja ma alokację na 10 itemów. Proszę o zmianę.

2021-04-27 11:14 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/repository/model/TechnologyGroup.java
> +    @SequenceGenerator(name = "technology_group_generator", sequenceName = "technology_group_seq",
W SQL'u zadeklarowano że sekwencja będzie miała zaalokowane 10 itemów. Zatem w mapowaniu powinniśmy również poinformować Hibernate'a że sekwencja ma alokację na 10 itemów. Proszę o zmianę.

2021-04-27 18:31 UTC, kari565 commented on src/main/java/com/intive/patronative/repository/model/Consent.java
> +@NoArgsConstructor
Zmieniłam we wszystkich klasach

2021-04-27 18:31 UTC, kari565 commented on src/main/java/com/intive/patronative/repository/model/Consent.java
> +    public Consent(final String text) {
Usunięte

2021-04-27 18:33 UTC, kari565 commented on src/main/java/com/intive/patronative/repository/model/Consent.java
> +            schema = "patronative", allocationSize = 1)
Zmienione we wszystkich klasach oraz zaktualizowałam plik db.sql aby było spójnie

2021-04-27 18:36 UTC, kari565 commented on src/main/java/com/intive/patronative/repository/model/User.java
> +    public User(final String login, final String userName, final String firstName,
@RequiredArgsConstructor będzie w tym przypadku konstruktorem bezparametrowym, bo pola nie są ani finalne ani NonNull. Żeby łatwiej tworzyło się obiekt z poziomu kodu dodałam @Builder, żeby nie trzeba było używać setterów.

2021-04-27 18:45 UTC, kari565 commented on src/main/java/com/intive/patronative/repository/model/User.java
> +@Entity
Zamieniłam na @Data zgodnie ze wskazówkami w pozostałych klasach, ale myślę, że lepiej byłoby zostawić własne konstruktory. Nie widzę możliwości, żeby w Lomboku tworzyć konstruktory tylko dla określonych pól, zakładając, że nie są one finalne. Inaczej trzeba będzie używać setterów do ustawiania wartości tych pól.

2021-04-28 19:06 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/repository/model/Consent.java
> +    @SequenceGenerator(name = "consent_generator", sequenceName = "consent_seq",
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: sequence [`patronative`.`consent_seq`] defined inconsistent increment-size; found [1] but expecting [10]

2021-04-28 19:28 UTC, kari565 commented on src/main/java/com/intive/patronative/repository/model/Consent.java
> +    @SequenceGenerator(name = "consent_generator", sequenceName = "consent_seq",
Zmieniłam plik db.sql. Trzeba znowu usunąć tabele i użyć nowego pliku do ich stworzenia. Przydałoby się też wyedytować data.sql, bo teraz nie będzie poprawnie dodawał danych do tabelek (inne wartości id).

2021-04-29 13:45 UTC, patronage-java-leaders-2021 requested changes

2021-04-29 13:45 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/repository/model/Consent.java
> +    @Column(name = "id", updatable = false, nullable = false)
Ponieważ używasz `@Id` dodatkowe mapowanie nie jest wymagane. Zmiana powinna zostać rozpropagowana na pozostaje wystąpienia.

2021-04-29 13:45 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/repository/model/Project.java
> +    private int year;
Ponieważ w bazie danych "year" może być nullem, powinniśmy to odzwierciedlić również w modelu - stąd zmień proszę z value na Object dla pola year.

2021-04-29 14:49 UTC, patronage-java-leaders-2021 approved these changes

2021-04-29 15:33 UTC, merged