IP2-439 - handle error when value is not allowed in enum
intive/patronage21-java pull request #36
Opened 2021-04-26 21:48 UTC by KrzysztofPawlak

2021-04-27 07:32 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/validation/EnumExceptionConverter.java
> +package com.intive.patronative.validation;
Zmieniłbym pakiet na converter, który w projekcie już się znajduje

2021-04-27 13:38 UTC, patronage-java-leaders-2021 requested changes

2021-04-27 13:38 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/validation/EnumExceptionConverter.java
> +public class EnumExceptionConverter {
Weryfikację poprawności wartości dla danego typu można zrealizować przy pomocy ądmotacji `@JsonDeserialize` i dostarczenia customowej implementacji deserializera. W przypadku gdy parsowanie się nie uda, wówczas można rzucić odpwiednim wyjątkiem z już dostępnych podając odpowiednią treść komuniaktu (np.: dozwolone wartości). 
Przykład implementacji takiego customowego deserializera można znaleźć tutaj: https://dzone.com/articles/jackson-annotations-for-json-part-3-deserialization (sekcja poświęcona `@JsonDeserialize`).

2021-04-29 13:09 UTC, patronage-java-leaders-2021 requested changes

2021-04-29 13:09 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/deserializer/EnumDeserializer.java
> +public class EnumDeserializer<T extends Enum<T>> extends JsonDeserializer<T> implements ContextualDeserializer {
Zgodnie z dokumentacją, customowe deserializery nie powinny extendować bezpośrednio klasy abstrakcyjnej JsonDeserializer. Zamiast tego klasa powinna extendować StdDeserializer lub jej podtypy np.:  StdScalarDeserializer.
Przykład customowego deserializera znajdziesz na przykład tutaj: https://www.baeldung.com/jackson-deserialization
Najbliższy przykład tego co zaimplementowałeś znajdziesz tutaj: https://www.baeldung.com/jackson-deserialization#on-mapper

2021-05-03 17:23 UTC, kari565 approved these changes

2021-05-04 06:51 UTC, patronage-java-leaders-2021 requested changes
Starałem się sprawdzić czy to działa i puściłem request na 
http://localhost:8080/frontend-api/users?firstName=dsa&lastName=dsa&username=dsa&role=CANDIDATE1
i nie wydaje mi się żeby działało to poprawnie albo coś źle zrobiłem proszę o sprawdzenie :)

https://www.baeldung.com/spring-type-conversions może być użyć GenericConverter ?

2021-05-04 07:56 UTC, kari565 requested changes
Rzeczywiście Deserializer nie działa. W projekcie obecny jest również UserRoleConverter, który działa zamiast niego.

2021-05-04 08:11 UTC, KrzysztofPawlak commented
proszę o sprawdzenie tego polu na obiekcie, a nie na request param. np konwerter nie działał mi na takim polu w obiekcie dlatego ten deserializer

2021-05-04 08:18 UTC, KrzysztofPawlak commented
używa się tego oznaczając pole: @JsonDeserialize(using = EnumDeserializer.class)

2021-06-11 07:07 UTC, patronage-java-leaders-2021 requested changes

2021-06-11 07:07 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/deserializer/EnumDeserializer.java
> +            final var message = "Allowed values: " + Arrays.toString(this.enumType.getEnumConstants()).replaceAll("^.|.$", "");
Proszę o lokalizację komunikatów błędów wykorzystując funkcjonalność dodaną w ramach zadania IP2-791.

2021-06-11 07:07 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/dto/registration/UserRegistrationRequestDTO.java
> +    @JsonDeserialize(using = EnumDeserializer.class)
Aktualnie w projekcie mamy do dyspozycji convertery np.: `UserStatusConverter` i `UserRoleConverter`. Wprowadzając zaproponowany przez Ciebie mechanizm, należy zmianę rozpropagować w pozostałych obszarach aplikacji gdzie znajdzie ona zastosowanie. Proszę o zmianę i dodanie testów poprawności działania rozwiązania. W razie pytań lub wątpliwości zapraszam do kontaktu.

2021-06-11 07:08 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/deserializer/EnumDeserializer.java
> +    public EnumDeserializer() {
W jakim celu został dodany ten konstruktor?

2021-06-21 23:00 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/dto/registration/UserRegistrationRequestDTO.java
> +    @JsonDeserialize(using = EnumDeserializer.class)
wyżej napisałem dlaczego deserializer

2021-06-24 15:37 UTC, patronage-java-leaders-2021 requested changes

2021-06-24 15:37 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/deserializer/EnumDeserializer.java
> +            return Enum.valueOf(this.enumType, jsonParser.getText().toUpperCase());
Dodaj proszę zabezpieczenie na NPE gdy `jsonParser.getText().` będzie nullem.

2021-06-25 14:49 UTC, patronage-java-leaders-2021 approved these changes

2021-06-25 14:51 UTC, merged