IP2-350 - create docker image
intive/patronage21-java pull request #38
Opened 2021-04-27 09:30 UTC by lzolkiewski

added Dockerfile
fixed warnings by adding: implementation 'com.google.code.findbugs:jsr305:3.0.2'

2021-05-04 05:48 UTC, patronage-java-leaders-2021 approved these changes

2021-05-04 07:16 UTC, kari565 approved these changes

2021-05-04 08:38 UTC, patronage-java-leaders-2021 requested changes

2021-05-04 08:38 UTC, patronage-java-leaders-2021 commented on docker-compose.yml
> +    restart: always
Proszę o usunięcię konfiguracji dotyczącej restartu kontenera, ponieważ jeśli wystąpi błąd nie chcemy aby Docker próbował podnosić i tak nie działającą aplikację.

2021-05-04 08:38 UTC, patronage-java-leaders-2021 commented on build.gradle
> +	implementation 'com.google.code.findbugs:jsr305:3.0.2'
Proszę o informację w ramach jakiego zadania została dodana ta zależność? Z góry dziękuję za informację.

2021-05-04 08:38 UTC, patronage-java-leaders-2021 commented on README.md
> +4) Start docker container containing application with a database:
docker-compose służy do skonfigurowania i uruchomienia wielokontenerowego środowiska. Stąd proszę o zmianę w dokumentacji i wskazanie na podniesienie prawie kompletnego zestawu elementów budujących aplikację.

2021-05-05 11:17 UTC, patronage-java-leaders-2021 approved these changes

2021-05-05 11:19 UTC, merged