Wip ip2 223 - search user with repository
intive/patronage21-java pull request #39
Opened 2021-04-29 09:45 UTC by KrzysztofPawlak

2021-04-29 14:46 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/controller/frontend/UserFrontController.java
> -        return ResponseEntity.ok(userService.searchUser(new UserSearchDTO(firstName, lastName, username, role)));
Tutaj powinny zostać @ReuestParam

2021-04-29 16:33 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/controller/frontend/UserFrontController.java
> -        return ResponseEntity.ok(userService.searchUser(new UserSearchDTO(firstName, lastName, username, role)));
tu jakby któryś z liderów mógł coś dorzucić bo mam dylemat.

2021-04-30 10:07 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/service/UserService.java
>          log.info("Called userService");
Można to usunąć już

2021-04-30 10:11 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/controller/frontend/UserFrontController.java
> +import org.springframework.web.bind.annotation.*;
tutaj nie są nam potrzebne wszystkie importy

2021-05-03 11:04 UTC, kari565 commented on src/main/java/com/intive/patronative/mapper/UserMapper.java
> +                .build();
Zastanawiam się czy tutaj potrzebne jest tworzenie klasy UserMapper. Czy te metody nie mogły być w UserDTO i UsersDTO jako static factory method?

2021-05-04 05:53 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/mapper/UserMapper.java
> +                .build();
Na pewno to mogłaby być metoda statyczny i na pewno trzeba usunąć @Component ponieważ nie ma sensu wciągania tego do konteksu Spring'a. Z tego co pamiętam to mieliśmy robić osobne mappery dlatego pewnie jest to w osobnej klasie

2021-05-04 09:42 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/repository/specification/UserSpecification.java
> +    }
Nie jestem pewien czy ten konstruktor jest ci potrzebny

2021-05-04 09:49 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/repository/specification/UserSpecification.java
> +    private static Predicate getInCaseSensitiveILikePredicate(final String value, final String fieldName,
Można by nadać temu nazwę getLikePredicate, lub caseInsensitiveLikePredicate

2021-05-04 11:20 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/controller/frontend/UserFrontController.java
> -        return ResponseEntity.ok(userService.searchUser(new UserSearchDTO(firstName, lastName, username, role)));
@KrzysztofPawlak : proszę o rozwinięcie Twojego poprzedniego komentarza. Z góry dziękuję.

2021-05-04 12:29 UTC, patronage-java-leaders-2021 requested changes

2021-05-04 12:29 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/UserService.java
> +    public UsersDTO searchUser(final UserSearchDTO userSearchDTO) {
Metoda w nazwie wskazuje że szuka użytkownika, natomiast zwraca użytkowników. Proszę o ustalenie przeznaczenia tej metody, ponieważ od tego zależy jej implementacja.

2021-05-04 12:29 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/UserService.java
> +        final List<User> fetchedUsers = userRepository.findAll(specification);
Ponieważ parametr metody pozwala na pola ustawione na null, w jednym z przypadków może zostać przekazany obiekt z pustymi polami. Proszę o zastanowienie się, w jaki sposób w tym przypadku powinna zadziałać logika metody - pozwolić na pobranie z bazy danych rekordów (jeśli tak to jakich?) czy też zwrócić pusty obiekt?

2021-05-04 12:29 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/repository/UserRepository.java
> +    List<User> findAll(Specification<User> specification);
JpaRepository pozwala nam na zbudowanie kryteriów wyszukiwania przy pomocy nazwy metody. Aktualna implementacja dostarczona w ramach tego pull request'u zakłada że wszystkie parametry są połączone logicznie ANDem. Tym samym można ją zastąpić  korzystając z własności Spring JPA i napisać findAllByName...(String name,....) dodając do nazwy metody i jej parametrów kryteria wyszukiwania, co znacznie uprości implementację. W razie pytań lub wątpliwości zapraszam do kontaktu.

2021-05-06 17:08 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/repository/specification/UserSpecification.java
> +    }
jest ok, jak są same statyczne metody. Prywatny konstruktor nie pozwala tworzyć takiej klasy co i tak nie ma sensu. Nie ma przez to wątpliwości jak to używać / wywoływać.

2021-05-08 17:14 UTC, lzolkiewski approved these changes

2021-05-09 22:50 UTC, kari565 commented on src/main/java/com/intive/patronative/mapper/UserMapper.java
> +                user.getLogin() != null ? user.getLogin() : null,
Czy tu nie wyjdzie to samo co jakby dać po prostu user.getLogin()?

2021-05-09 22:50 UTC, kari565 commented on src/main/java/com/intive/patronative/controller/api/UserController.java
> +import com.intive.patronative.dto.profile.UserDTO;
Aplikacja się nie buduje:
/home/gradle/src/src/main/java/com/intive/patronative/controller/api/UserController
.java:25: error: incompatible types: @javax.validation.Valid com.intive.patronative.dto.profi
le.UserDTO cannot be converted to com.intive.patronative.dto.model.UserDTO

2021-05-09 22:50 UTC, kari565 commented on src/main/java/com/intive/patronative/controller/frontend/UserFrontController.java
> +import com.intive.patronative.dto.profile.UserDTO;
Aplikacja się nie buduje:
 /home/gradle/src/src/main/java/com/intive/patronative/controller/frontend/UserFront
Controller.java:36: error: incompatible types: @javax.validation.Valid com.intive.patronative
.dto.profile.UserDTO cannot be converted to com.intive.patronative.dto.model.UserDTO

2021-05-14 06:15 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, BigDecimal>, UserSearchRepository {
Czemu to tak zostało zrobione ?

2021-05-14 10:02 UTC, patronage-java-leaders-2021 requested changes

2021-05-14 10:25 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/mapper/UserMapper.java
> +public class UserMapper {
znaczy wyżej w review (10 dni temu) mam napisane, że to nie powinno angażować kontekstu springa, wiec metody statyczne.

2021-05-14 10:26 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/mapper/UserMapper.java
> +            return new UserDTO(null, null, null, null, null, null);
tak z tym się gryzłem czy null powinien być zwracany, ale ok

2021-05-18 20:36 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/mapper/UserMapper.java
> +        );
a jaki jest z tego zysk?

2021-05-18 20:44 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/repository/UserSearchRepository.java
> +public interface UserSearchRepository {
inaczej trzeba by było zaimplementować wszystkie pozostałe metody z extends JpaRepository

2021-05-18 21:15 UTC, kari565 commented on src/main/java/com/intive/patronative/repository/UserSearchRepositoryImpl.java
> +    public List<User> findAllUsers(final UserSearchDTO userSearchDTO) {
Nie lepiej to zastąpić metodą:
`findByFirstNameLikeIgnoreCaseAndLastNameLikeIgnoreCaseAndLoginLikeIgnoreCaseAndRoleName(String firstName, String lastName, String Login, String name)` ?

Ewentualnie jeśli metoda za długa to może by użyć @Query z SQLem?

2021-05-18 21:50 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/validation/UserSearchValidator.java
> +        return (login != null) && (!UserValidator.isLoginValid(login) || isLengthInvalid(login)) ?
no tak już było

2021-05-18 21:58 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/repository/UserSearchRepositoryImpl.java
> +    public List<User> findAllUsers(final UserSearchDTO userSearchDTO) {
tu będą też sprawdzane nulle w zapytaniu (chyba), a jak dodasz kolejne 4 parametry? Chcieliśmy obiektowo. Poza tym sqlem też łatwo z nulli nie wybrniesz

2021-05-18 21:58 UTC, KrzysztofPawlak commented on src/test/java/com/intive/patronative/controller/frontend/UserFrontControllerTest.java
> +        verify(userService, times(1)).searchUsers(any(), any(), any(), any());
dobrze wiedzieć, ale raczej to w niczym nie przeszkadza. Nawet pomocne info

2021-05-19 18:28 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/validation/UserSearchValidator.java
> +        return (login != null) && (!UserValidator.isLoginValid(login) || isLengthInvalid(login)) ?
te sprawdzanie było jednak potrzebne dla lazy evaluation, UserValidator odrzuca te z nullem

2021-05-19 18:49 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/validation/UserSearchValidator.java
> +        return (login != null) && (!UserValidator.isLoginValid(login) || isLengthInvalid(login)) ?
te sprawdzanie było jednak potrzebne dla lazy evaluation, UserValidator odrzuca te z nullem. Postaram się chociaż tych negacji pozbyć

2021-05-21 14:52 UTC, closed without merging