Wip ip2 457
intive/patronage21-java pull request #42
Opened 2021-05-01 16:20 UTC by KrzysztofPawlak

2021-05-03 18:41 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/repository/specification/UserSpecification.java
> +                    getInCaseSensitiveILikePredicate(other, "userName", criteriaBuilder, root));
a username to nie to?

2021-05-03 18:43 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/repository/specification/UserSpecification.java
> +        }
racja

2021-05-04 09:14 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/mapper/UserMapper.java
> +    public UserDTO toDtoUserSearched(final User user) {
Mógłbyś to zostawić po prostu toUserDTO

2021-05-04 09:14 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/mapper/UserMapper.java
> +    public UsersDTO toDtoUsersSearched(final List<User> users) {
Tu podobnie myślę, że toUsersDTO by wystarczyło

2021-05-04 10:53 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/repository/specification/UserSpecification.java
> +                .and(hasRole(userSearchDTO.getRole()));
Chyba brakuje tu hasOther

2021-05-04 11:01 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/validation/UserSearchValidator.java
> +    }
Nie jestem pewien czy ta funkcja ma sens

2021-05-05 22:01 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/validation/UserSearchValidator.java
> +    }
a czemu nie, jest to powielone x razy?

2021-05-05 22:04 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/repository/specification/UserSpecification.java
> +                .and(hasRole(userSearchDTO.getRole()));
nie, other miało być alternatywą dla podania tych 3. Podając other zostanie zignorowane firstname, lastname, login.

2021-05-05 22:43 UTC, kari565 commented on src/main/java/com/intive/patronative/validation/UserSearchValidator.java
> +                " dash/space allowed in case of two-part surname," +
Teraz chyba wyszukiwanie będzie po loginie zamiast po username.

2021-05-05 22:43 UTC, kari565 commented on src/main/java/com/intive/patronative/repository/specification/UserSpecification.java
> +                    getInCaseSensitiveILikePredicate(other, "userName", criteriaBuilder, root));
Teraz chyba wyszukiwanie będzie po loginie zamiast po username.

2021-05-06 13:46 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/validation/UserSearchValidator.java
> +                " dash/space allowed in case of two-part surname," +
to jest jeszcze całe do zmiany, jak podstawowe wyszukiwanie będzie już ok.

2021-05-14 10:18 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/validation/UserSearchValidator.java
> +    }
W tym miejscu nie potrzebujesz podawać tych długości skoro masz je już w klasie chyba, że planowałeś je zmieniać

2021-05-18 15:38 UTC, patronage-java-leaders-2021 requested changes

2021-05-18 15:38 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/validation/UserSearchValidator.java
> +                ((userSearchData.length() < userSearchDataMinLength) ||
Zaproponowany przez Ciebie zapis można udopornić na niezamierzone błędy i podnieść jego czytelność łącząc dwa kryteria długośc stringa przy pomocy  `&&` (konieczna jest również zmiana kierunków porównania). Tym samym otrzymasz przedział liczbowy w którym powinna znaleźć się długość Stringa userSearchData któego wartość liczbowa powinna być zawarta między minLength a maxLength. Proszę o zmianę :).

2021-05-18 21:42 UTC, kari565 commented on src/main/java/com/intive/patronative/validation/UserSearchValidator.java
>                  Optional.empty();
Czytelniej będzie:
```
return (firstName != null) && (!UserValidator.isFirstNameValid(firstName) || isLengthInvalid(firstName)) 
                ? Optional.of(new FieldError("String", "firstName", firstName, false, null, null, firstNameMessage)) 
                : Optional.empty();
```
Tak samo w innych metodach walidujących.

2021-05-18 21:42 UTC, kari565 commented on src/main/java/com/intive/patronative/validation/UserSearchValidator.java
>          return (lastName != null) && (!UserValidator.isLastNameValid(lastName) || isLengthInvalid(lastName)) ?
Niepotrzebny lastName != null. Jest to sprawdzane  w isLastNameValid. Tak samo w innych metodach walidujących.

2021-05-18 21:42 UTC, kari565 commented on src/main/resources/application.yml
> +          max: 20
20 znaków chyba nie wystarczy na niektóre nazwiska, a tym bardziej na to co będzie wysyłane w other.

2021-05-18 21:42 UTC, kari565 commented on src/test/java/com/intive/patronative/controller/frontend/UserFrontControllerTest.java
> +        verify(userService, times(1)).searchUsers(any(), any(), any(), any(), any(), any());
verify ma domyślnie podany times(1), więc można użyć
`verify(userService).searchUsers(any(), any(), any(), any(),any(), any());`

2021-05-18 21:42 UTC, kari565 commented on src/main/java/com/intive/patronative/repository/UserSearchRepositoryImpl.java
> +                createLikePredicate(other, "login", criteriaBuilder, root));
Tutaj nie wyszuka przy wpisaniu imienia i nazwiska, np. "anna nowa". Dodatkowo przy wpisaniu "anna n" zwraca błąd walidacji.

2021-05-18 21:42 UTC, kari565 commented on src/main/java/com/intive/patronative/repository/UserSearchRepositoryImpl.java
>      public List<User> findAllUsers(final UserSearchDTO userSearchDTO) {
Czy nie lepiej zastąpić całą tę implementację JPA Query method lub Named Query? Tak jak napisałam w kometarzu do poprzedniego review.

2021-05-18 22:12 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/repository/UserSearchRepositoryImpl.java
> +                createLikePredicate(other, "login", criteriaBuilder, root));
aha to trzeba poprawić

2021-05-18 22:14 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/validation/UserSearchValidator.java
>                  Optional.empty();
no trochę tak

2021-05-21 07:55 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/validation/UserSearchValidator.java
>                  Optional.empty();
@KrzysztofPawlak : proszę o uwzględnienie proponowanych zmian w kodzie lub odniesienie się do komentarzy z uzasadnieniem dlaczego zmiana nie zostanie zrealizowana. Dziękuję.

2021-05-21 08:46 UTC, patronage-java-leaders-2021 requested changes

2021-05-21 08:46 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/repository/UserSearchRepositoryImpl.java
> +        final List<Predicate> predicates = addPredicates(userSearchDTO, criteriaBuilder, root);
Proponuję zmianę nazwy metody na `buildPredicates()` lub `createPredicates()`, ponieważ efektem pracy metody jest przygotowanie listy predykatów które zostaną nastepnie przekazane do CriteriaQuery. `Nazwa addPredicates` sugeruje że wykonujesz operację na rzecz obiektu który jest przekazany do metody.

2021-05-21 08:46 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/validation/UserSearchValidator.java
> +        final var technologyGroupMessage = "Letters or numbers," +
Połącz proszę dwa Stringi "Letters..." i "dash..."  w jeden.

2021-05-21 10:18 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/repository/UserSearchRepositoryImpl.java
> +        final boolean isContainsSpace = other.contains(SPACE);
Tu mógłbyś to nazwać containsSpace albo isSpace

2021-05-21 10:30 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/validation/UserSearchValidator.java
> +                getMinMaxCharactersMessage();
To ci się zmieści w jednej linii bez problemu

2021-05-21 10:31 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/validation/UserSearchValidator.java
> +                getMinMaxCharactersMessage();
To również w jednej linii może być

2021-05-21 10:53 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/validation/UserValidator.java
> +    private static final int MAX_OTHER_LENGTH = 64;
Można to wynieść do pliku konfiguracyjnego

2021-05-21 13:30 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/validation/UserValidator.java
> +    private static final int MAX_OTHER_LENGTH = 64;
powinno zostać bo jest to użyte do matchera który jest statyczny

2021-05-21 13:31 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/repository/UserSearchRepositoryImpl.java
> +        final boolean isContainsSpace = other.contains(SPACE);
z is na poczatku to jest good practices, isSpace sugeruje że coś jest spacja lub nie, a to nie ten przypadek

2021-05-21 14:28 UTC, patronage-java-leaders-2021 approved these changes

2021-05-21 14:39 UTC, lzolkiewski approved these changes

2021-05-21 14:44 UTC, kari565 approved these changes

2021-05-21 14:47 UTC, merged