IP2-454 - add group fetching operation
intive/patronage21-java pull request #43
Opened 2021-05-05 11:18 UTC by kari565

2021-05-05 11:49 UTC, patronage-java-leaders-2021 requested changes

2021-05-05 11:49 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/GroupService.java
> +    public GroupsDTO getGroups() {
Wyciągnij zmienną przed return'em dla czytelności kodu w ten deseń

    public GroupsDTO getGroups() {
        log.info("Called getGroups");
        final var yourVariable = groupRepository.findAll().stream()
                .map(TechnologyGroup::getName)
                .collect(Collectors.toList());
        return new GroupsDTO(yourVariable);
    }

2021-05-05 11:49 UTC, patronage-java-leaders-2021 commented on src/test/java/com/intive/patronative/controller/frontend/GroupFrontControllerTest.java
> +class GroupFrontControllerTest {
Test (klasa) jest do usunięcia, w tym wypadku sprawdzimy tylko czy działają adnotacje Spring'owe i od razu zwracamy mock'a,

2021-05-05 11:49 UTC, patronage-java-leaders-2021 commented on src/test/java/com/intive/patronative/service/GroupServiceTest.java
> +    public void getGroups_shouldReturnGroupsFromRepository(final List<TechnologyGroup> groups,
Nazwy metod testowych powinny zaczynaś się od słowa "should" lub powinny być skonstruowane jako "whenSomeCondition_thenSomeResult". Proszę o zmianę nazwy metody.

2021-05-05 11:49 UTC, patronage-java-leaders-2021 commented on src/test/java/com/intive/patronative/service/GroupServiceTest.java
> +    private static Stream<Arguments> provideDataForGetGroups() {
Proszę o bardziej opisową, a mniej techniczną, nazwę metody. Tak żeby wskazywała na funkcjonalność którą dostarcza, lub pokazywała powiązanie z konkretną metodą testową.

2021-05-05 21:57 UTC, KrzysztofPawlak approved these changes

2021-05-06 04:33 UTC, patronage-java-leaders-2021 approved these changes

2021-05-06 08:57 UTC, merged