IP2-525 - create projects' endpoint
intive/patronage21-java pull request #45
Opened 2021-05-07 20:12 UTC by lzolkiewski

2021-05-08 06:41 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/service/ProjectService.java
> +    public ProjectResponseDTO getProjects() {
wydaje mi się, że albo metoda powinna mieć w nazwie currentYear, albo ten year powinien być przekazywany w parametrze metody.

2021-05-08 08:27 UTC, kari565 commented on src/main/java/com/intive/patronative/dto/ProjectResponseDTO.java
> +import java.util.List;
Niepotrzebny import

2021-05-08 11:00 UTC, kari565 commented on src/main/java/com/intive/patronative/repository/ProjectRepository.java
> +    List<String> getDistinctProjectNamesByYear(Integer year);
Tu można zrobić `Set<Project> findDistinctByYear(int year);`

2021-05-08 11:03 UTC, kari565 reviewed
Wydaje mi się, że brakuje ProjectFrontControllera. nasz FE będzie używał tej operacji.

2021-05-08 13:15 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/repository/ProjectRepository.java
> +    List<String> getDistinctProjectNamesByYear(Integer year);
też się nad tym zastanawiałem i poprzednie chyba jest odpowiedniejsze, bo pobiera dokładnie to co potrzebuje

2021-05-08 13:21 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/service/ProjectService.java
> +        return new ProjectResponseDTO(projectRepository.getDistinctProjectNamesByYear(Calendar.getInstance().get(Calendar.YEAR)));
z tym to mam dalej jeszcze wątpliwości, bo załóżmy będzie test do tego i test takiej metody jest zależny od daty w środku, więc takie testy mogą się za jakiś czas wyłożyć. Ale to może niech liderzy się wypowiedzą

2021-05-08 15:26 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/repository/ProjectRepository.java
> +    List<String> getDistinctProjectNamesByYear(Integer year);
Wydaje mi się że findDistinct szuka po kluczach, a one powinny się zawsze różnić 
po dodaniu do bazy projektu o nazwie Projekt I, nazwa projektu już istnieje, zwrócone zostaną oba projekty, 
nie wiem czy jest możliwość przy takim podejściu zaznaczenia po którym polu powinien sprawdzać.

2021-05-08 17:10 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/service/ProjectService.java
> +        return new ProjectResponseDTO(projectRepository.getDistinctProjectNamesByYear(Calendar.getInstance().get(Calendar.YEAR)));
W przypadku gdy w bazie danych nie ma projektu z konkretnego roku to zwracana jest pusty set co nie powinno spowodować wykładania się testów.

2021-05-11 06:33 UTC, patronage-java-leaders-2021 requested changes

2021-05-11 06:33 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/repository/ProjectRepository.java
> +    List<String> getDistinctProjectNamesByYear(Integer year);
Próbowałem odpalić to lokalnie i dostawałem błąd 
"For queries with named parameters you need to use provide names for method parameters. Use @Param for query method parameters..."
żeby to działało musiałem dodać 
(@Param("year") Integer year);

Druga sprawa możemy użyć **int year** bo nie będziemy nic robić z obiektem i zawsze będzie podany rok

2021-05-12 20:25 UTC, patronage-java-leaders-2021 approved these changes

2021-05-13 09:56 UTC, kari565 approved these changes

2021-05-13 16:43 UTC, merged