IP2-524 - add roles to project fetching operation
intive/patronage21-java pull request #46
Opened 2021-05-08 11:06 UTC by kari565

2021-05-08 17:29 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/repository/ProjectRoleRepository.java
> +import org.springframework.data.jpa.repository.Query;
nadmiarowy import

2021-05-08 17:29 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/repository/ProjectRoleRepository.java
> +import java.util.List;
nadmiarowy import

2021-05-08 17:29 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/repository/ProjectRepository.java
> +    Set<Project> findDistinctByYear(int year);
Jak dodasz do bazy danych projekt o takiej samej nazwie jak już istniejący zostaną zwrócone 2 projekty o tych samych nazwach, a tak miało nie być

2021-05-08 17:33 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/mapper/ProjectMapper.java
> +                        .collect(Collectors.toSet())))
project.getProjectRoles().stream().map(ProjectRole::getName).collect(Collectors.toSet())) możesz to wynieść do osobnego mappera teoretycznie, bo mapujesz tu role projektowe ale to pewnie według uznania

2021-05-09 21:42 UTC, kari565 commented on src/main/java/com/intive/patronative/repository/ProjectRepository.java
> +    Set<Project> findDistinctByYear(int year);
Ale tylko w przypadku gdy te 2 projekty są z tego samego roku. Jeżeli wpiszesz temu projektowi inny rok niż ten, z którym go porównujesz to wyświetli się jeden (w zależności od roku). Z tego co pamiętam nazwy projektów mogą się powtarzać, ale w danym roku powinny być unikalne.

2021-05-09 21:54 UTC, kari565 commented on src/main/java/com/intive/patronative/repository/ProjectRepository.java
> +    Set<Project> findDistinctByYear(int year);
Ale i tak nazwy projektów miały być unikalne w danym roku. A co jak 2 projekty o tej samej nazwie miałyby różne role? To wtedy zwróci się tylko jeden z tych projektów i wyświetlą się tylko jego role?

2021-05-09 22:09 UTC, kari565 commented on src/main/java/com/intive/patronative/mapper/ProjectMapper.java
> +                .map(project -> new ProjectWithRolesDTO(project.getName(), project.getProjectRoles()
Pole name w tabelce project jest not null. Nie powinno być nullem.

2021-05-11 07:52 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/mapper/ProjectMapper.java
> +                .map(project -> new ProjectWithRolesDTO(project.getName(), project.getProjectRoles()
A co jeżeli ktoś będzie chciał pobrać dane z 3033 roku ;) ?

2021-05-12 20:35 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/mapper/ProjectMapper.java
> +                .map(project -> new ProjectWithRolesDTO(project.getName(), project.getProjectRoles()
Sprawdziłem lokalnie jest dobrze

2021-05-12 20:35 UTC, patronage-java-leaders-2021 approved these changes

2021-05-17 07:23 UTC, lzolkiewski approved these changes

2021-05-19 12:49 UTC, patronage-java-leaders-2021 requested changes

2021-05-19 14:23 UTC, patronage-java-leaders-2021 approved these changes

2021-05-19 17:59 UTC, lzolkiewski approved these changes

2021-05-19 19:22 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/mapper/ProjectMapper.java
> +        return projects.stream()
brakuje null checka

2021-05-19 21:45 UTC, merged