IP2-357 - add user deactivation
intive/patronage21-java pull request #47
Opened 2021-05-10 13:01 UTC by lzolkiewski

2021-05-12 21:03 UTC, patronage-java-leaders-2021 requested changes

2021-05-12 21:03 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/UserService.java
> +        final var status = statusRepository.findByName(UserStatus.INACTIVE.name()).orElseThrow(() ->
Tutaj musimy cofnąć się do klasy Status i dodać dla UserStatus

    @Enumerated(EnumType.STRING)
    private UserStatus name;

Dzięki temu będziemy mogli używać UserStatus.INACTIVE już bez name(), Trzeba usunąć linijkę 50 i 51 ponieważ wiemy, że chcemy ustawić status jako INACTIVE dla usera więc proszę usuń wyciąganie statusu z bazy danych.

No i przy okazji tego testy do poprawy bo będzie świeciło się na czerwono ;)

2021-05-12 21:03 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/exception/StatusNotFoundException.java
> +public class StatusNotFoundException extends EntityNotFoundException {
To nam raczej też już nie będzie potrzebne zakładamy, że te statusy już będą na bazie danych i basta

2021-05-12 21:03 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/repository/StatusRepository.java
> +    Optional<Status> findByName(final String name);
Ta metoda też raczej do usunięcia jeżeli nie jest nidzie używana

2021-05-18 13:50 UTC, patronage-java-leaders-2021 requested changes

2021-05-18 13:50 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/UserService.java
> +        if (isUserActive(user)) {
Ze względu na rzucanie wyjątków przez mechanizmy walidacji aplikacji oraz anotację `Transactional` na metodzie, wydziel proszę do osobnej metody część która realizuje zapis do bazy danych, i opatrz ją proszę odpowiednią anotacją.

2021-05-18 13:50 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/UserService.java
> +    @Transactional(readOnly = true)
Metoda nie odwołuje się do bazy danych, zatem anotacje można śmiało usunąć :).

2021-05-18 13:50 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/UserService.java
> +    @Transactional(readOnly = true)
Adnotacja nie jest potrzebna ponieważ nie utrwalasz danych.

2021-05-20 08:06 UTC, kari565 approved these changes

2021-05-20 18:35 UTC, kari565 reviewed
Brakuje dozwolonej metody PATCH w CorsConfig. W tej chwili nie da się deaktywować użytkownika z naszej reactowej aplikacji.

2021-05-20 20:46 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/service/UserService.java
> +            storeUserInDatabase(user);
wydaje mi się że jak jest już wydzielona metoda to edycja również powinna to wywyływać

2021-05-20 20:46 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/service/UserService.java
> +    public void deactivateUser(final String login) {
nie wiem może nadmiarowe ale ByLogin

2021-05-20 20:46 UTC, KrzysztofPawlak commented on src/test/java/com/intive/patronative/service/UserServiceTest.java
> +        Mockito.when(userRepository.findByLogin(login)).thenReturn(Optional.empty()); //login not found in database
po co ten coment?

2021-05-21 14:53 UTC, patronage-java-leaders-2021 requested changes

2021-05-21 14:53 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/UserService.java
> +                && user.getStatus().getName().equals(UserStatus.ACTIVE);
Aby uniknąć NPE porównania na ogół robimy stała.equals(....). Przy aktualnej implementacji getName() może zwrócić null'a i.... NPE gotowy. Proszę o zmianę.

2021-05-21 14:53 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/UserService.java
> +            user.setStatus(statusRepository.findByName(UserStatus.INACTIVE).orElse(user.getStatus()));
Proponuję również zmianę z `.orElse()` na `.orElseGet()`, co pozwoli na wykonanie bloku else wtedy kiedy na prawdę będzie taka potrzeba :).

2021-05-21 15:43 UTC, patronage-java-leaders-2021 approved these changes

2021-05-21 20:48 UTC, kari565 approved these changes

2021-05-21 21:08 UTC, merged