IP2-678 - drop username
intive/patronage21-java pull request #51
Opened 2021-05-17 16:52 UTC by KrzysztofPawlak

2021-05-18 13:08 UTC, patronage-java-leaders-2021 requested changes

2021-05-18 13:08 UTC, patronage-java-leaders-2021 commented on src/main/resources/db/migration/V1_0_2__drop_user_name.sql
> +ALTER TABLE patronative.user DROP COLUMN user_name;
Usunięcie kolumny z tabeli to jedna kwestia. Lecz wprowadzając zmiany w strukturze danych w bazie danych należy również pamiętać o odpowiednich zmianach również w modelu bazodanowym po stronie aplikacji. Dodatkowo należy również zwryfikować czy nie są potrzebne jakieś dodatkowe zmiany w innych częściach aplikacji, a jeśli są one wymagane, należy je wykonać.
Proszę dokończenie zadania.

2021-05-21 11:38 UTC, lzolkiewski approved these changes

2021-05-21 14:21 UTC, patronage-java-leaders-2021 approved these changes

2021-05-21 14:31 UTC, merged