IP2-679 - fixes in UserValidator
intive/patronage21-java pull request #52
Opened 2021-05-18 08:05 UTC by lzolkiewski

2021-05-18 13:04 UTC, patronage-java-leaders-2021 requested changes

2021-05-18 13:04 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/validation/UserValidator.java
> +    private static final String BASE_GITHUB_LINK = "https://www.github.com/";
Zarówno `github.com` jak i `www.github.com` są poprawnymi adresami domowymi GitHub'a.

2021-05-18 13:04 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/validation/UserValidator.java
> +        return (login == null) || (isUsernameValid(login))
Dlaczego walidujemy login jako username?

2021-05-18 15:10 UTC, patronage-java-leaders-2021 approved these changes

2021-05-18 16:52 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/validation/UserValidator.java
>      private static final String BIO_MESSAGE = "Bio up to 512 characters";
masz na górze 512 bio to można podstawić.

2021-05-18 16:52 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/validation/UserValidator.java
> +    private static final String FIRST_NAME_MESSAGE = "Only letters, 2 to 30 letters";
ten range jest również w regex, może do osobnej stałej sama wartość, aby zmieniać w 1 miejscu? Podobnie przy innych polach

2021-05-20 07:28 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/validation/UserValidator.java
> +    private static final String EMAIL_MESSAGE = "Example e-mail: example.Mail123@mail.com, username part " + MIN_EMAIL_USERNAME_LENGTH + " to " + MAX_EMAIL_USERNAME_LENGTH + " characters";
co za różnica czy będzie tam gmail czy mail?

2021-05-20 07:29 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/validation/UserValidator.java
> +            "[a-zA-Z0-9]+([-?][a-zA-Z0-9]+)*$");
I o ile się nie mylę tak też jest

2021-05-20 07:44 UTC, kari565 commented on src/main/java/com/intive/patronative/validation/UserValidator.java
> +            "[a-zA-Z0-9]+([-?][a-zA-Z0-9]+)*$");
No racja, chciałam przetestować, ale mi się nie udało uruchomić projektu.

2021-05-20 11:59 UTC, kari565 approved these changes

2021-05-20 13:25 UTC, merged