IP2-671 - return user's image and status
intive/patronage21-java pull request #53
Opened 2021-05-18 08:37 UTC by lzolkiewski

2021-05-18 12:52 UTC, patronage-java-leaders-2021 requested changes

2021-05-18 12:52 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/mapper/UserMapper.java
> +                .image(user.getProfile() != null ? user.getProfile().getImage() : null)
Użyj proszę Optional'a żeby zrealizować sprawdzenie i pobieranie odpowiedniej wartości. Będzie prościej i czytelniej :).

2021-05-18 12:52 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/mapper/UserMapper.java
> +                .bio(user.getProfile() != null ? user.getProfile().getBio() : null)
Użyj proszę Optional'a żeby zrealizować sprawdzenie i pobieranie odpowiedniej wartości. Będzie prościej i czytelniej :).

2021-05-18 12:52 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/mapper/UserMapper.java
> +                .status(user.getStatus() != null ? user.getStatus().getName() : null)
Użyj proszę Optional'a żeby zrealizować sprawdzenie i pobieranie odpowiedniej wartości. Będzie prościej i czytelniej :).

2021-05-19 14:21 UTC, kari565 approved these changes

2021-05-19 19:24 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/mapper/UserMapper.java
>          return (user == null) ? UserProfileDTO.builder().build() : UserProfileDTO.builder()
przy nullu nie powinno się budować obiektu z nullowymi polami.

2021-05-20 20:23 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/dto/UserProfileDTO.java
> +    String status;
znaczy mamy status jako enum to czemu nie użyć? Jest też już rola jako enum + converter do niej, więc myśle że powinno być jednakowo.

2021-05-21 14:32 UTC, patronage-java-leaders-2021 approved these changes

2021-05-21 15:02 UTC, merged