IP2-682 - UserMapper and ProjectMapper fix
intive/patronage21-java pull request #54
Opened 2021-05-18 09:57 UTC by lzolkiewski

added UserMapperTest
found vulnerabilities fixed

2021-05-18 12:47 UTC, patronage-java-leaders-2021 requested changes

2021-05-18 12:47 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/mapper/UserMapper.java
> +        return (user == null) ? null : UserProfileDTO.builder()
Proszę o modyfikację implementacji z wykorzystaniem Optional, np.:
Optional.ofNullable(...).map(...).orElse();
Będzie ona o wiele bardziej czytelna :). Dziękuję :).

2021-05-18 12:47 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/mapper/ProjectMapper.java
> +        return (projects == null)
Proszę o wykorzystanie Optional do zaimplementowania logiki metody. Pomimo zmiany w implementacji, sygnatura metody nie powinna ulec zmianie.

2021-05-18 12:47 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/mapper/ProjectMapper.java
>          return (project == null)
Proszę o wykorzystanie Optional do zaimplementowania logiki metody. Pomimo zmiany w implementacji, sygnatura metody nie powinna ulec zmianie.

2021-05-18 21:58 UTC, kari565 commented on src/main/java/com/intive/patronative/mapper/ProjectMapper.java
>      }
Metodę można krócej zapisać:
```
private Optional<ProjectRole> getProjectRole(final Project project) {
        return Optional.ofNullable(project)
                .map(Project::getProjectRoles)
                .flatMap(roles -> roles.stream().findAny());
    }
```

2021-05-18 21:58 UTC, kari565 commented on src/test/java/com/intive/patronative/mapper/UserMapperTest.java
> +                new HashSet<>(Collections.singletonList(new Project()))));
Dla czytelności tego co się dzieje w testach można by zastosować konwencję given when then: https://javastart.pl/b/java/given-when-then-w-testach/

2021-05-19 13:42 UTC, patronage-java-leaders-2021 commented on src/test/java/com/intive/patronative/mapper/UserMapperTest.java
> +                new HashSet<>(Collections.singletonList(new Project()))));
Zgadzam się z propozycją @kari565 . Wprowadźmy takie podejście do każdego nowego testu który pojawi się u nas w aplikacji. Jeśli uważacie że jest taka potrzeba, możemy temat przedyskutować szerzej tuż po daily.

2021-05-19 14:08 UTC, kari565 approved these changes

2021-05-19 22:09 UTC, merged