IP2-697 user validation code refactor
intive/patronage21-java pull request #58
Opened 2021-05-24 13:54 UTC by lzolkiewski

2021-05-24 14:27 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/validation/UserValidator.java
> +        final var firstNamePattern = Pattern.compile("^[a-zA-ZĄąĆćĘęŁłŃńÓóŚśŹźŻż]{" + minFirstNameLength + "," +
Jak się nie mylę Pattern.compile powinno być poza metodami, jak było wcześniej. Validator ma adnotacje @Component więc jest singletonem. Bo tak skutkować tak, że będzie za każdym wywołaniem metody to mielone (performance)

2021-05-24 15:05 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/validation/Validator.java
> +public class Validator {
można dać abstract

2021-05-24 15:24 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/validation/UserSearchValidator.java
> +public class UserSearchValidator extends Validator {
extends tu nie jest potrzebny, bo wstrzyknięty jest UserValidator userValidator wiec tam masz ta metodę. Cały Validator na razie nie jest potrzebny bo obecnie tylko UserValidator z niego by korzystał.

2021-05-25 08:23 UTC, patronage-java-leaders-2021 requested changes

2021-05-25 08:23 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/validation/UserSearchValidator.java
>  @PropertySource("classpath:application.yml")
Ponieważ dane wstrzykiwane przy pomocy `@Valule` są pobierane z defaultowego pliku konfiguracyjnego, nie ma potrzeby dodawania adnotacji `PropertySource'.

2021-05-25 08:23 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/validation/UserSearchValidator.java
> +    @Autowired
Ponieważ wstrzykujesz przez konstruktor adnotacja `@Autowired` nie jest potrzebna. Pole powinno być `private final`.

2021-05-25 08:23 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/validation/Validator.java
> +public class Validator {
Jeśli wprowadzamy ogólną klasę walidatora po której będą dziedziczyły konkretne walidatory, to klasa nadrzędna powinna dostarczać wspólną dla wszystkich klas potomnych logikę. Przejrzyj proszę `UserValidator` i `UserSearchValidator` i znajdź metodę lub metody wspólne dla obu walidatorów i umieść proszę ich implementację tutaj.

2021-05-25 08:23 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/validation/Validator.java
> +public class Validator {
@KrzysztofPawlak : Przy podejściu które proponujesz, jaka byłaby wówczas rola klasy `Validator` mając na uwadze całą strukturę walidatorów?

2021-05-26 11:00 UTC, patronage-java-leaders-2021 requested changes
Proszę o uwzględnienie w kodzie sugestii pozostałych osób z zespołu lub odniesienie się do nich w formie odpowiedzi na komentarze. Dziękuję.

2021-05-26 11:14 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/validation/UserSearchValidator.java
> +    protected List<FieldError> getFieldErrors(final UserSearchDTO userSearchDTO) {
Zmiana wynikła z mojej nieuwagi gdy wracałem do rozwiązania z przed dodania Validatora
Zostało to zmienione

2021-05-26 11:16 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/validation/UserSearchValidator.java
>      private int userSearchDataMinLength;
Te settery są używane przy testowaniu

2021-05-26 11:21 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/validation/UserValidator.java
> +        final var firstNamePattern = Pattern.compile("^[a-zA-ZĄąĆćĘęŁłŃńÓóŚśŹźŻż]{" + minFirstNameLength + "," +
Gdybym zrobił to co proponujesz, w każdym pattern'ie możliwa długość maksymalna i minimalna, w przypadku gdy dane pobierane są z pliku konfiguracyjnego, wynosiła by 0

2021-05-26 18:29 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/validation/UserValidator.java
> +        final var firstNamePattern = Pattern.compile("^[a-zA-ZĄąĆćĘęŁłŃńÓóŚśŹźŻż]{" + minFirstNameLength + "," +
hmm to może nie warto wynosić tego do pliku konfiguracyjnego. Tak jak już mówiłem ja widzę więcej wad niż zalet korzystania z tego.

2021-05-26 19:00 UTC, KrzysztofPawlak commented on src/main/resources/application.yml
> +    first-name:
zamiast powielać w 2 miejscach, wg mnie lepiej wrzucić to w ValidationConstraintsProvider

2021-05-26 19:46 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/validation/UserValidator.java
> +        final var firstNamePattern = Pattern.compile("^[a-zA-ZĄąĆćĘęŁłŃńÓóŚśŹźŻż]{" + minFirstNameLength + "," +
Przerabiam walidację żeby było poprawnie i masz rację źle to zrobiłem  dane zostaną w pliku konfiguracyjnym jednak inaczej będę tego używał, a same matchery pozostaną poza metodami  czyli tak jak mówiłeś od początku

2021-05-26 19:47 UTC, lzolkiewski commented on src/main/resources/application.yml
> +    first-name:
Nie do końca rozumiem do czego nawiązujesz

2021-05-26 20:03 UTC, KrzysztofPawlak commented on src/main/resources/application.yml
> +    first-name:
czy to nie jest to samo?
    login:
      length:
        min: 2
        max: 15

    public static final int MIN_LOGIN_LENGTH = 2;
    public static final int MAX_LOGIN_LENGTH = 15;

2021-05-26 20:13 UTC, lzolkiewski commented on src/main/resources/application.yml
> +    first-name:
Przecież to jest jedynie na potrzeby testowania jakbyś chciał to połączyć ?
Na spotkaniu mówiliśmy o wystawianiu ograniczeń, które nie pochodzą z bazy danych, w pliku konfiguracyjnym i po to przerabiam całą tą walidację
Czym różniła by się ta propozycja od poprzedniego rozwiązania z wyjątkiem nowej klasy?

2021-05-26 20:22 UTC, KrzysztofPawlak commented on src/main/resources/application.yml
> +    first-name:
no spoko nie spojrzałem że to do testów

2021-05-26 20:38 UTC, KrzysztofPawlak commented on src/main/resources/application.yml
> +    first-name:
ale poza tym to wciąż konfiguracje zawsze trzeba zmieniać w 2 miejscach. Inaczej testy się wyłożą.

2021-05-27 12:02 UTC, kari565 commented on src/main/resources/application.yml
>            max: 125
Wydaje mi się, że tutaj się powtarza wartość minimalna w `validators.user.other.length.min`, natomiast wartość mksymalna jest inna, niż ta sprawdzana w UserValidatorze: `private static final int MAX_OTHER_LENGTH = 162;`

W ogóle wygląda, że teraz w każde pole wyszukiwania można wpisać od 2 do 125 znaków, tak wynika ze zwracanej wiadomości, a sprawdzane są inne wartości dla długości tych pól. Np. dla firstName sprawdzane jest czy mieści się w przedziale od 2 do 30, ale jak wpiszę 80, to wtedy mam komunikat, że "Letters only, minimum 2 characters, maximum 125 characters".

2021-05-27 12:09 UTC, lzolkiewski commented on src/main/resources/application.yml
> +        min: 2
Maksymalna długość została określona na podstawie danych z bazy

2021-05-27 12:15 UTC, kari565 commented on src/main/resources/application.yml
> +        min: 2
Aha, to jest zsumowana maksymalna długość imienia, nazwiska i loginu w bazie plus 2 na spacje?

2021-05-27 13:13 UTC, lzolkiewski commented on src/main/resources/application.yml
> +        min: 2
Tak :)

2021-05-27 13:24 UTC, lzolkiewski commented on src/main/resources/application.yml
>            max: 125
Jeżeli chodzi o minimalną wartość zostawiłbym to powielone bo nie jest to to samo więc może się zmienić w przyszłości 
Co do maksymalnej wartości to tu nie jestem pewien teoretycznie to mogło by zostać w konfigu i wyznaczać nam customową wartość górną, a to co jest w kodzie górną wartość z bazy danych ale nie zwróciłem na to uwagi w trakcie pisania tego więc to muszę jeszcze sprawdzić

2021-06-01 11:50 UTC, kari565 approved these changes

2021-06-01 13:57 UTC, patronage-java-leaders-2021 approved these changes

2021-06-01 15:53 UTC, merged