IP2-114 create ApiUserController
intive/patronage21-java pull request #6
Opened 2021-03-23 19:03 UTC by barbara-tyndorf

2021-03-23 20:08 UTC, kari565 commented on src/main/java/com/intive/patronative/controller/ApiUserController.java
> +    }
Można użyć Lombokowego @RequiredArgsConstructor.

2021-03-23 20:10 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/controller/ApiUserController.java
> +    public void updateUser(@Validated @RequestBody UserDTO userDTO){
Wydaje mi się, że w tym miejscu powinno być @Valid zamiast @Validated

2021-03-23 20:10 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/controller/ApiUserController.java
> +public class ApiUserController {
Myślę, że prościej było by nadawać nazwy od zaczynając od nazw modeli bez "Api".
Będzie bardziej przejrzyście w aplikacji. 
Chyba, że planujemy jakieś inne kontrolery wtedy nie mam uwag.

2021-03-23 20:14 UTC, KrzysztofPawlak requested changes

2021-03-23 20:14 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/controller/ApiUserController.java
> +        userService.updateUser(userDTO);
wydaje mi się że wystarczy userService.update, wiadomo że usera

2021-03-23 20:45 UTC, kari565 requested changes
Powinniśmy robić pull requesty do brancha dev, a nie do main.

2021-03-24 09:27 UTC, barbara-tyndorf commented on src/main/java/com/intive/patronative/controller/ApiUserController.java
> +    public void updateUser(@Validated @RequestBody UserDTO userDTO){
właśnie wiem, ale trzeba dodać zależność, a ja w gradle jeszcze nie ogarniam. Wiem, że ktoś z Was robił walidację, to po mergu powinno działać z @Valid

2021-03-24 09:28 UTC, barbara-tyndorf commented on src/main/java/com/intive/patronative/controller/ApiUserController.java
> +    }
miałam przez tą adnotację ostatnio problemy z zapętleniem, więc trochę się jej boję :P ale póki mamy jeden serwis to w sumie ok, mogę zmienić

2021-03-24 09:29 UTC, barbara-tyndorf commented on src/main/java/com/intive/patronative/controller/ApiUserController.java
> +public class ApiUserController {
no właśnie tak zrozumiałam, że będziemy mieli różne kontrolery do api i do frontu stąd ta nazwa

2021-03-24 09:30 UTC, barbara-tyndorf commented on src/main/java/com/intive/patronative/controller/ApiUserController.java
> +        userService.updateUser(userDTO);
w sumie racja

2021-03-24 14:44 UTC, patronage-java-leaders-2021 requested changes

2021-03-24 14:44 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/controller/ApiUserController.java
> +public class ApiUserController {
@barbara-tyndorf , @lzolkiewski: część przygotowana w Javie będzie udostępniała swoje zasoby dla:
- warstwy prezentacji danych zrealizowanej w oparciu o Node.JS'a, oraz
- dla innych konsumentów, np.: dla modułu grup technologicznych.
Stąd właśnie, aby wprowadzić rozgraniczenie (granulację), endpointy które nie będą udostępniane dla warstwy prezentacji, mają na początku `/api`.

@barbara-tyndorf: proponuję zmienić nazwę klasy na `UserControleler`, i umieścić ją w odpowiednim pakiecie, który będzie wskazywał na przeznaczenie klasy (np.: com.intive.patronative.controller.api, lub innej, zaproponowanej przez Ciebie). Może się bowiem zdarzyć, że w przyszłości będziemy mieli podobnie nazwany kontroler, lecz dedykowany dla warstwy prezentacji.

2021-03-29 08:24 UTC, lzolkiewski approved these changes
Wygląda w porządku

2021-03-29 10:25 UTC, patronage-java-leaders-2021 approved these changes

2021-03-29 10:28 UTC, patronage-java-leaders-2021 commented
Przed dodaniem brancha do dev'a zrób proszę squasha, żeby zmiana weszła jako jeden commit. Jeśli będziesz miała jakiekolwiek pytania lub wątpliwości, daj proszę znać :).

2021-03-29 10:46 UTC, KrzysztofPawlak approved these changes

2021-03-29 11:10 UTC, kari565 approved these changes

2021-03-31 09:03 UTC, merged