IP2-766 - create endpoint for updating profile image
intive/patronage21-java pull request #61
Opened 2021-05-31 13:00 UTC by kari565

2021-05-31 13:50 UTC, patronage-java-leaders-2021 requested changes

2021-05-31 13:50 UTC, patronage-java-leaders-2021 commented on build.gradle
> +    implementation 'junit:junit:4.12'
Aktualnie w projekcie używamy JUnit'a 5. Proszę o informacje co spowodowało dodanie starszej wersji JUnita, co w rezultacie przekłada się na obecność dwóch różnych wersji JUnit'a w projekcie?

2021-05-31 13:50 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/UserService.java
> +        final byte[] profileImage = convertImageToBytes(image);
Proponuję aby konwersję obrazka wykonać dopiero po uprzednim znalezieniu użytkownika. Pozwoli to na uniknięcie sytuacji gdzie konwersja obrazka została wykonana, ale nie znaleziono użytkownika którego zdjęcie profilowe powinno zostać zaktualizowane.

2021-05-31 13:50 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/UserService.java
> +        final byte[] profileImage;
Zmiennna powinna zostać zainicjalizowana.

2021-05-31 13:50 UTC, patronage-java-leaders-2021 commented on src/main/resources/application.yml
> +    max-swallow-size: -1
Czy defaultowa wartość 2MB nie będzie wystarczająca? Co było powodem dla wyłączenia mechanizmu weryfikacji maksymalnej wielkości uploadowanych danych?

2021-05-31 21:21 UTC, kari565 commented on build.gradle
> +    implementation 'junit:junit:4.12'
Dodane przez pomyłkę. Już usunęłam.

2021-05-31 22:38 UTC, kari565 commented on src/main/resources/application.yml
> +    max-swallow-size: -1
Chciałam, żeby w przypadku plików powyżej 2MB błąd był obsługiwany przez ExceptionHandlera i zwracany był kod 422 zamiast 500, tak jak dla pliku powyżej 512KB. 
Teraz dodałam jeszcze obsługę SizeLimitExceededException i  widzę, że działa bez tej konfiguracji, więc ją usuęłam.

2021-06-01 08:31 UTC, lzolkiewski approved these changes

2021-06-01 13:45 UTC, patronage-java-leaders-2021 approved these changes

2021-06-03 11:04 UTC, merged