IP2-584 - user's project role edition
intive/patronage21-java pull request #65
Opened 2021-06-09 16:40 UTC by lzolkiewski

2021-06-10 16:28 UTC, patronage-java-leaders-2021 requested changes

2021-06-10 16:28 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/mapper/ProjectMapper.java
> +        return CollectionUtils.isEmpty(projects)
Zamień proszę 'ternary operator' na if'a - poprawi to czytelność. Wykonanie mapowania realizowane przez `projects.stream()...` byłoby wykonane gdy `if(!Collections.isEmpty(projects)) {...}`.

2021-06-10 16:28 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/mapper/ProjectMapper.java
> +                .map(entityRolesInProject -> Optional.ofNullable(entityRolesInProject)
W tym przypadku proszę o analogiczną zmianę jak w przypadku metody `getProjectDTOsWithoutRole()`. 
Dodatkowo, jeśli wiesz że rolesInProject może zawierać null'a, to przed wykonaniem mapowania należy go odfiltrować na przykład przy pomocy: `.filter(Objects::nonNull)`. Wówczas pozbędziesz się `Optional.ofNullable(entityRolesInProject)`. Co uprości całego stream'a. Proszę o zmianę.

2021-06-10 16:28 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/mapper/ProjectMapper.java
> +                .map(entityProject -> Optional.ofNullable(entityProject)
Jeśli wiesz że `projects` może zawierać null'a (używasz Set'a), to należy go odfiltorwać przed wykonaniem mapowania na przykład przy pomocy: `filter(Objects::nonNull)`. To pozwoli uprościć implementację. Proszę o zmianę.

2021-06-10 16:28 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/mapper/ProjectMapper.java
> +                        .map(entityProject -> Optional.ofNullable(entityProject)
Analogicznie jak wcześniej, jeśli null'e są spodziewane, to powinniśmy je odfiltrować zanim wykonamy mapowanie :).

2021-06-10 16:28 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/mapper/RolesInProjectMapper.java
> +        projectsDTO.forEach(projectDTO -> Optional.ofNullable(projectDTO)
Całość można uprościć używając stream'a i filtrowania null'a (użycie Set'a), zanim wykonasz mapowanie. Sytuacja naalogiczna jak w ProjectMapper'ze.

2021-06-10 16:28 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/mapper/RolesInProjectMapper.java
> +                .filter(project -> (projectName.compareTo(project.getName()) == 0))
Ponieważ sprawdzasz czy nazwy są sobie równe proponuję zamienić użyte leksykograficzne porównanie, na `equalsIgnoreCase()`. Proponowane podejście pozwoli Tobie nie zwracać uwagi na wielkość liter, co jest oczekiwanym działaniem. W razie pytań lub wątpliwości, zapraszam do kontaktu.

2021-06-10 16:28 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/mapper/RolesInProjectMapper.java
> +                .filter(projectRole -> (roleName.compareTo(projectRole.getName()) == 0))
I tutaj również `equalsIgnoreCase` będzie lepszym podejściem zamiast użycie `compareTo`.

2021-06-13 19:24 UTC, kari565 commented on src/test/java/com/intive/patronative/service/UserRegistrationServiceTest.java
> +        userService = new UserService(userSearchValidator, technologyGroupsValidator, userValidator, userMapper,
Nie lepiej użyć @InjectMocks?

2021-06-13 19:24 UTC, kari565 commented on src/main/java/com/intive/patronative/service/UserService.java
> +    public void rolesInProjectDeleteAllPreviousAndStoreNewInDatabase(final User user, final Set<RolesInProject> rolesInProject) {
Długa nazwa metody, jeśli występuje "And" to może lepiej byłoby podzielić funkcjonalność na dwie metody?

2021-06-14 07:19 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/converter/UserStatusConverter.java
> +        } catch (IllegalArgumentException exception) {
Skoro final nie jest konieczny w tym bloku to chciałem ujednolicić oba konwertery.

2021-06-14 09:19 UTC, lzolkiewski commented on src/test/java/com/intive/patronative/service/UserRegistrationServiceTest.java
> +        userService = new UserService(userSearchValidator, technologyGroupsValidator, userValidator, userMapper,
Tutaj autor chciał chyba polegać na właściwym obiekcie mappera dlatego zostały zainicjowane nie mockowane stąd chyba takie rozwiązanie.

2021-06-14 09:22 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/service/UserService.java
> +    public void rolesInProjectDeleteAllPreviousAndStoreNewInDatabase(final User user, final Set<RolesInProject> rolesInProject) {
Tu chodziło mi o to by w przypadku błędu na bazie danych w przypadku zapisu, usunięcie również zostało cofnięte

2021-06-15 11:44 UTC, patronage-java-leaders-2021 requested changes

2021-06-15 11:44 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/mapper/ProjectMapper.java
> +    private Set<ProjectDTO> getProjectDTOsWithAndWithoutRoles(final Set<ProjectDTO> withoutRoles, final Set<ProjectDTO> withRoles) {
Nazwa metody sugeruje że zwrócony `Set<ProjectDTO>` będzie zawierał projekty z rolami i bez. Podczas gdy w implementacji zwracana jest instancja Set'a która została przekazana jako parametr metody. Proszę o zmianę nazwy metody na bardziej czytelną.

2021-06-15 11:44 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/mapper/ProjectMapper.java
> +        if (CollectionUtils.isEmpty(withoutRoles)) {
Sprawdzasz wymagalność tylko pierwszego parametru, z jakiej przyczny pomijasz drugi? Przy aktualnej implementacji NPE jest możliwy gdy wthRoles będzie nullem. Proszę o poprawkę.

2021-06-15 11:44 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/mapper/ProjectMapper.java
> +            withoutRoles.remove(projectDTOWithoutRole);
Czemu ma służyć ta implementacja? Dlaczego podmieniasz zawartość Seta przekazanego jako parametr metody, a później tą samą referencję  zwracasz jako efekt pracy metody? Tym samym zmieniasz oryginalne dane a powinieneś utworzyć nowy obiekt będący wynikiem przekazanych danych wejściowych do metody.
Metoda powinna utworzyć osobną instancję `Set<ProjectDTO>` która powinna zostać zasilona utworzonymi danymi. Proszę o poprawkę.

2021-06-15 11:44 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/mapper/RolesInProjectMapper.java
> +        final var projectsMap = getAvailableProjects(user, projectsDTO);
W nazwie zmiennej nie powinien zawierać się jej typ (tutaj wskazuje na to dopisek Map). Jeśli trzeba skorzystać z takich zabiegów, lepszym wyjściem będzie zastąpienie `var` jasno zdefiniowanym typem danych. Proszę o zmianę i o refactor nazwy zmiennych.

2021-06-15 11:44 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/UserService.java
> +    public void rolesInProjectDeleteAllPreviousAndStoreNewInDatabase(final User user, final Set<RolesInProject> rolesInProject) {
Proponuję zmianę nazwy metody na coś krótszego, bo aktualnie be zaglądania w implementację trudno zidentyfikować co ona robi :). Proszę o zmianę.

2021-06-16 07:35 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/mapper/ProjectMapper.java
> +        Set<ProjectDTO> withAndWithoutRoles = new HashSet<>(withoutRoles);
Aby zbudować listę projektów będących wynikiem działania metody należy zadeklarować pusty `Set<ProjectDTO>`. Następnie dodawać do niego tylko niepuste itemy z Set'ów przekazanych jako parametry metody. Tak wypracowany wynik działania metody należy następnie zwrócić. Proszę o poprawkę. W razie pytań lub wątpliwości - daj proszę znać :).

2021-06-17 16:23 UTC, patronage-java-leaders-2021 requested changes

2021-06-17 16:23 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/mapper/ProjectMapper.java
> +        final var withoutRole = getProjectDTOsWithoutRole(entityProjects);
Na podstawie aktualnej implementacji metody widzę że chcesz przygotować listę dostępnych projektów. 
Zatem proponuję trochę inne podejście, aby temat trochę sobie uprościć :
`getProjectDTOsWithoutRole(entityProjects).stream()
                .map(ProjectDTO::getName)
                .filter(StringUtils::isNotBlank)
                .map(StringUtils::trim)
                .collect(Collectors.toList());` - 
tym samym dostaniemy listę nazw niepustych nazw projektów które dodatkowo zostały wytrymowane.
Analogiczne podejście zastosować w przypadku `withRoles`.
Następnie dodać do siebie te dwie listy usuwając duplikaty (można to zrobić przy pomocy Stream API) i tak wypracowany wynik zwrócić jako rezultat pracy metody.
W razie pytań lub wątpliwości, zapraszam do kontaktu :).

2021-06-24 15:32 UTC, patronage-java-leaders-2021 approved these changes

2021-06-25 05:24 UTC, kari565 approved these changes

2021-06-25 07:53 UTC, merged