IP2-924 - added synchronization
intive/patronage21-java pull request #69
Opened 2021-06-14 12:18 UTC by lzolkiewski

2021-06-14 13:01 UTC, kari565 approved these changes

2021-06-15 11:09 UTC, patronage-java-leaders-2021 requested changes

2021-06-15 11:09 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/validation/TechnologyGroupsValidator.java
> +    private void setTechnologyGroupMaxNameLengthMessage() {
Wstrzyknięty validationHelper powinien być użyty w metodzie  `checkTechnologyGroupName` do wypraowania treści komunikatu (np.: final var message = validationHelper.getFormatterMessage(...)...` a następnie zamiast `getFieldError(technologyGroupName, TECHNOLOGY_GROUP_MAX_NAME_LENGTH_MESSAGE);` będzie `getFieldError(technologyGroupName, message);`. Proszę o zmianę.
Tym samym metoda uruchamiana w `@PostConstruct` nie będzie potrzebna. 
Proszę o zmianę.

2021-06-15 11:09 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/validation/UserSearchValidator.java
> +                validationHelper.getMinMaxCharactersMessage(minSearchDataLength, userValidator.getMaxLoginLength()));
Proponuję aby wywołania `validationHelper.getMinMaxCharactersMessage(minSearchDataLength, userValidator.getMaxLoginLength())` i podobne, zastąpić zmienną w metodzie do którego będzie przypisany wynik metody. Poprawi to czytelność kodu.

2021-06-16 07:17 UTC, patronage-java-leaders-2021 approved these changes

2021-06-16 09:13 UTC, kari565 approved these changes

2021-06-16 09:14 UTC, merged