Wip ip2 115
intive/patronage21-java pull request #7
Opened 2021-03-23 19:08 UTC by barbara-tyndorf

2021-03-23 19:57 UTC, lzolkiewski submitted a review, later dismissed
Wygląda w porządku.

2021-03-23 20:04 UTC, KrzysztofPawlak approved these changes

2021-03-23 20:04 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/service/UserService.java
> +
nadmiarowa linia

2021-03-23 20:04 UTC, KrzysztofPawlak commented on src/main/resources/application.yml
> +
ta linia też chyba nic nie zmienia

2021-03-23 21:27 UTC, kari565 requested changes
Powinniśmy robić pull requesty do brancha dev, a nie do main.

2021-03-24 13:17 UTC, lzolkiewski approved these changes

2021-03-24 14:48 UTC, patronage-java-leaders-2021 approved these changes

2021-03-24 14:48 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/service/UserService.java
> +
@barbara-tyndorf : po usunięciu nadmiarowej linii o której wspomniał @KrzysztofPawlak , zmiana może zostać zmerge'owana.

2021-03-25 16:49 UTC, merged