IP2-102 - Added user display controller
intive/patronage21-java pull request #8
Opened 2021-03-23 22:41 UTC by LukaszCzeronko

2021-03-24 07:23 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/controller/UserDisplayController.java
> +    @Autowired
lepiej jak będzie przez konstruktor, lub adnotacją

2021-03-24 08:17 UTC, patronage-java-leaders-2021 requested changes

2021-03-24 08:17 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/controller/UserDisplayController.java
> +    public ResponseEntity<?> displayUsersByRole(@RequestParam User.Role userRole) {
Dlaczego używasz unknown wildcard'a (<?>) w przypadku gdy znamy typ zwracanego obiektu?

2021-03-24 08:17 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/controller/UserDisplayController.java
> +        return new ResponseEntity<>(userDisplayService.getUserByRole(userRole), HttpStatus.OK);
Aktualna implementacja, niezależnie od tego czy zwrócona odpowiedź zawiera dane czy nie, zawsze zwracasz HTTP status 200. Proponowałbym zastanowić się jak powinna reagować aplikacja w przypadku gdy danych nie znaleziono albo gdy podane parametry wyszukiwania są niepoprawne (walidacja nie przechodzi). W tym ostatnim przypadku zwrócenie status odpowiedzi "OK" jest sprzeczne z komunikatem błędu.

2021-03-24 08:33 UTC, LukaszCzeronko commented on src/main/java/com/intive/patronative/controller/UserDisplayController.java
> +        return new ResponseEntity<>(userDisplayService.getUserByRole(userRole), HttpStatus.OK);
Z tego co pamiętam zakładaliśmy, że na razie postępujemy z "happy flow". Czyli z tego co przeczytałem na stronie wiki "In the context of software or information modeling, a happy path (sometimes called happy flow) is a default scenario featuring no exceptional or error conditions.". Więc zakładam, że wszystkie warunki początkowe są zgodne i prowadzą tylko do rozwiązania które nie niesie ze sobą błędów.

2021-03-24 08:50 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/controller/UserDisplayController.java
> +public class UserDisplayController {
Myślę że lepszym było by stworzenie bardziej ogólnej nazwy dla kontrolera.

2021-03-24 22:41 UTC, LukaszCzeronko commented on src/main/java/com/intive/patronative/controller/UserDisplayController.java
> +    public ResponseEntity<?> displayUsersByRole(@RequestParam User.Role userRole) {
Jest to rozwiązanie tymczasowe, model user dto nadal nie jest zmergowane.

2021-04-06 06:44 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/controller/api/UserController.java
> +        if (userService.getUserByRole(userRole) == null || userService.getUserByRole(userRole).isEmpty()) {
wywołujesz tutaj 2 razy serwis mógłbyś dać wcześniej jakąś listę i wywoływać go tylko raz mniej dostępów do docelowej bazy danych

2021-04-06 06:45 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/controller/api/UserController.java
> +            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
Nie jestem przekonany co do odpowiedzi 404 ale tu musi się wypowiedzieć lider

2021-04-06 06:47 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/controller/api/UserController.java
> +            return new ResponseEntity<>(userService.getUserByRole(userRole), HttpStatus.OK);
Z tą linią masz 3-krotne odwołanie się do bazy danych w momencie gdy tę bazę będziemy posiadali w 1 metodzie.

2021-04-06 10:06 UTC, LukaszCzeronko commented on src/main/java/com/intive/patronative/controller/api/UserController.java
> +            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
@patronage-java-leaders-2021 Czy możecie pomóc w podjęciu decyzji która opcja jest lepsza: 

- HTTP 200 OK + pusta lista

- HTTP 404 NOT FOUND + bez body
 Myślę, że ta decyzja powinna obowiązywać we wszystkich komponentach.

2021-04-06 10:53 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/controller/api/UserController.java
> +            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
jest jescze opcja z noContent

2021-04-06 11:34 UTC, lzolkiewski approved these changes

2021-04-06 11:53 UTC, barbara-tyndorf commented on src/main/java/com/intive/patronative/controller/api/UserController.java
> +            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
ja jestem za 200 OK + pusta lista, bo zapytanie jest prawidłowe, tylko nie ma contentu do zwrócenia

2021-04-06 19:50 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/controller/api/UserController.java
> +        } else {
else nie jest potrzebny, to niżej i tak się wykona jak będzie pod if-em

2021-04-06 20:11 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/controller/api/UserController.java
> +    public ResponseEntity<List<UserDto>> getUserByRole(@Valid @RequestParam UserRole userRole) {
@Valid póki co jest nadmiarowy, @RequestParam można uprościć nazwę @RequestParam(name = "role")

2021-04-06 20:13 UTC, KrzysztofPawlak commented on src/main/java/com/intive/patronative/controller/api/UserController.java
> +        List<UserDto> users = userService.getUserByRole(userRole);
można dać final

2021-04-07 08:25 UTC, LukaszCzeronko commented on src/main/java/com/intive/patronative/controller/api/UserController.java
> +        } else {
wydaję mi się, że takowa forma jest bardziej przejrzysta

2021-04-07 08:27 UTC, LukaszCzeronko commented on src/main/java/com/intive/patronative/controller/api/UserController.java
> +    public ResponseEntity<List<UserDto>> getUserByRole(@Valid @RequestParam UserRole userRole) {
Nie wiem czy to jest uroszczenie. Obecna  forma wydaję się bardziej składna

2021-04-13 19:20 UTC, kari565 commented on src/main/java/com/intive/patronative/controller/api/UserController.java
> +    public ResponseEntity<List<UserDto>> getUserByRole(@Valid @RequestParam UserRole userRole) {
Operacja zwraca listę userów, więc lepiej byłoby nazwać metodę getUsersByRole.

2021-04-13 19:20 UTC, kari565 commented on src/main/java/com/intive/patronative/exception/UserRoleExceptionHandler.java
> +                apiError, apiError.getStatus());
Można by użyć varów i finali.

2021-04-13 19:20 UTC, kari565 commented on src/main/java/com/intive/patronative/model/ApiError.java
> +    private String message;
Można by użyć final na parametrach. Wtedy @AllArgsConstructor nie jest potrzebny. albo zamienić @Data na @Value i usunąć @AllArgsConstructor, żeby tworzyć obiekty niemutowalne.

2021-04-13 19:20 UTC, kari565 commented on src/main/java/com/intive/patronative/service/UserService.java
> +    public List<UserDto> getUserByRole(UserRole userRole) {
Metoda zwraca listę userów, więc lepiej byłoby nazwać metodę getUsersByRole.

2021-04-13 19:20 UTC, kari565 commented on src/main/java/com/intive/patronative/controller/api/UserController.java
> +            return new ResponseEntity<>(users, HttpStatus.OK);
Można to tak uprościć: 
return ResponseEntity.ok(users);

2021-04-22 07:08 UTC, closed without merging